"""Génère les packs éditoriaux V10, déterministement (aucune IA/aucun accès réseau).
Les variantes sont des exercices construits à partir de situations et calculs explicites.
Chaque exercice est accompagné de deux indices liés aux nombres/objets de sa question.
"""
import json, math, random, re
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / 'backend' / 'content'
PREFIX = '@@studysprint-blocks@@'

MATH_6 = [
 ('Nombres entiers et décimaux', 'Lire, comparer et encadrer les nombres décimaux.', 'Un nombre décimal se compose d’une partie entière et d’une partie décimale.', 'Comparer des décimaux', 'Pour comparer deux décimaux, aligne les chiffres des unités puis compare les dixièmes et les centièmes.', 'Encadrer un nombre', 'Entre deux entiers consécutifs, un nombre décimal est toujours encadré par sa partie entière et l’entier suivant.'),
 ('Addition et soustraction', 'Effectuer des calculs et résoudre des problèmes additifs.', 'Pose les nombres en alignant les unités et les virgules.', 'Calcul posé', 'Additionne ou soustrais séparément unités, dixièmes et centièmes.', 'Vérifier le résultat', 'Une soustraction se contrôle en ajoutant la différence au plus petit nombre.'),
 ('Multiplication et division', 'Calculer des produits et des quotients.', 'Un produit représente l’addition répétée d’un même nombre.', 'Division euclidienne', 'Le dividende est égal au produit du diviseur par le quotient, plus le reste.', 'Contrôler un calcul', 'Après une division, multiplie le quotient par le diviseur pour vérifier.'),
 ('Fractions et partage', 'Comprendre une fraction comme partage d’une unité.', 'Le dénominateur donne le nombre de parts égales ; le numérateur le nombre de parts choisies.', 'Fractions équivalentes', 'On obtient une fraction équivalente en multipliant numérateur et dénominateur par un même nombre non nul.', 'Fractions d’une quantité', 'Pour calculer une fraction d’un ensemble, commence par partager en parts égales.'),
 ('Proportionnalité', 'Reconnaître et utiliser un coefficient de proportionnalité.', 'Deux grandeurs sont proportionnelles si on passe de l’une à l’autre en multipliant toujours par le même coefficient.', 'Passage à l’unité', 'Calcule d’abord la valeur correspondant à une seule unité.', 'Tableau proportionnel', 'On peut multiplier une colonne par un facteur pour obtenir une autre colonne.'),
 ('Pourcentages simples', 'Calculer la part d’une quantité correspondant à 10 %, 25 % et 50 %.', 'Un pourcentage exprime une part sur cent.', 'Pourcentages usuels', '50 % correspond à la moitié, 25 % au quart et 10 % au dixième.', 'Pourcentage d’une quantité', 'Pour trouver une part, divise d’abord la quantité par 100 puis multiplie par le pourcentage.'),
 ('Longueurs et conversions', 'Convertir des distances du millimètre au kilomètre.', 'Chaque unité de longueur vaut dix fois l’unité immédiatement plus petite.', 'Passage de m à cm', 'Un mètre correspond à cent centimètres.', 'Vérification', 'Une même longueur a une valeur numérique plus grande dans une petite unité.'),
 ('Masses et conversions', 'Convertir et comparer des masses.', 'La masse d’un objet se mesure avec une balance.', 'Passage de kg à g', 'Un kilogramme correspond à mille grammes.', 'Vérification', 'Pour passer des grammes aux kilogrammes, divise par mille.'),
 ('Durées et horaires', 'Calculer des durées et convertir heures et minutes.', 'Une heure correspond à soixante minutes.', 'Calculer une durée', 'Transforme les horaires en minutes lorsque le calcul franchit une heure.', 'Contrôler', 'L’heure d’arrivée est égale à l’heure de départ plus la durée.'),
 ('Périmètres', 'Calculer le périmètre de figures simples.', 'Le périmètre est la longueur totale du contour d’une figure.', 'Rectangle', 'Pour un rectangle de longueur L et largeur l, P = 2 × (L + l).', 'Carré', 'Le périmètre d’un carré est égal à quatre fois la longueur de son côté.'),
 ('Aires du carré et du rectangle', 'Mesurer une surface en unités carrées.', 'L’aire représente la surface occupée par une figure.', 'Rectangle', 'Pour calculer l’aire du rectangle, multiplie la longueur par la largeur.', 'Carré', 'Pour un carré de côté c, l’aire vaut c × c.'),
 ('Volumes et pavés droits', 'Déterminer le volume d’un cube et d’un pavé droit.', 'Le volume mesure l’espace occupé par un solide.', 'Pavé droit', 'Volume = longueur × largeur × hauteur, avec trois longueurs dans la même unité.', 'Cube', 'Un cube de côté c a pour volume c × c × c.'),
 ('Angles et instruments', 'Identifier et mesurer des angles.', 'Un angle est formé par deux demi-droites de même origine.', 'Classification', 'Un angle aigu mesure moins de 90°, un angle droit 90° et un angle obtus entre 90° et 180°.', 'Angles complémentaires', 'Deux angles complémentaires ont une somme de 90°.'),
 ('Triangles et quadrilatères', 'Reconnaître et exploiter des propriétés de figures.', 'Un triangle comporte trois côtés et trois angles.', 'Triangles', 'La somme des angles d’un triangle est égale à 180°.', 'Quadrilatères', 'Un carré possède quatre côtés égaux et quatre angles droits.'),
 ('Tableaux et statistiques', 'Lire des données, trouver une fréquence et une moyenne simple.', 'Un tableau regroupe les effectifs ou les mesures d’une série.', 'Moyenne', 'Additionne toutes les valeurs puis divise par le nombre de valeurs.', 'Étendue', 'L’étendue est la différence entre la plus grande valeur et la plus petite.'),
]
MATH_5 = [
 ('Nombres relatifs : comparer', 'Repérer les nombres positifs et négatifs sur une droite graduée.', 'Un nombre négatif est plus petit que zéro et qu’un nombre positif.', 'Comparer des relatifs', 'Parmi deux nombres négatifs, celui qui a la plus grande distance à zéro est le plus petit.', 'Opposés', 'Deux nombres opposés ont la même distance à zéro et des signes contraires.'),
 ('Addition et soustraction de relatifs', 'Calculer avec des nombres positifs et négatifs.', 'Soustraire un nombre revient à ajouter son opposé.', 'Même signe', 'Pour additionner deux nombres de même signe, additionne les distances et conserve le signe.', 'Signes opposés', 'Soustrais les distances à zéro et conserve le signe du nombre ayant la plus grande distance.'),
 ('Comparer les fractions', 'Comparer et simplifier des fractions.', 'Deux fractions peuvent représenter la même quantité.', 'Dénominateur commun', 'Pour comparer deux fractions, écris-les avec un même dénominateur positif.', 'Simplifier', 'Divise le numérateur et le dénominateur par un diviseur commun non nul.'),
 ('Additionner des fractions', 'Additionner et soustraire des fractions simples.', 'On ne peut additionner les numérateurs que lorsque les dénominateurs sont identiques.', 'Mettre au même dénominateur', 'Multiplie numérateur et dénominateur par un même nombre non nul.', 'Fin du calcul', 'Une fois les dénominateurs identiques, additionne les numérateurs et simplifie.'),
 ('Multiplier des fractions', 'Multiplier des fractions et utiliser des inverses.', 'Pour multiplier deux fractions, multiplie leurs numérateurs puis leurs dénominateurs.', 'Produit', 'La fraction a/b multipliée par c/d vaut ac/bd.', 'Simplification', 'Tu peux simplifier un numérateur avec un dénominateur avant le produit.'),
 ('Priorités opératoires', 'Utiliser correctement les parenthèses et les opérations.', 'Effectue les opérations entre parenthèses avant les autres.', 'Priorité', 'Multiplications et divisions sont prioritaires sur additions et soustractions.', 'Contrôler', 'Recopie l’expression à chaque étape en ne modifiant que les opérations calculées.'),
 ('Premiers calculs littéraux', 'Utiliser une lettre pour représenter un nombre.', 'Une lettre peut représenter un nombre inconnu ou variable.', 'Réduire', 'On peut additionner uniquement les termes de même nature : 2x + 3x = 5x.', 'Développer', 'La distributivité donne k(a + b) = ka + kb.'),
 ('Équations simples', 'Résoudre des équations du premier degré simples.', 'Une équation est une égalité contenant un nombre inconnu.', 'Conserver l’égalité', 'Tu peux ajouter, soustraire, multiplier ou diviser les deux membres par un même nombre non nul.', 'Vérification', 'Remplace l’inconnue dans l’équation de départ pour vérifier la solution.'),
 ('Proportionnalité et vitesse', 'Calculer des distances et des vitesses constantes.', 'La vitesse est la distance parcourue pendant une unité de temps.', 'Vitesse', 'v = d / t, avec des unités cohérentes.', 'Distance', 'À vitesse constante, distance = vitesse × durée.'),
 ('Pourcentages et remises', 'Calculer une réduction et un nouveau prix.', 'Une remise de p % retire p centièmes du prix initial.', 'Valeur de la remise', 'Remise = prix initial × pourcentage / 100.', 'Prix final', 'Soustrais la remise du prix initial ; ne confonds pas remise et prix payé.'),
 ('Angles des triangles', 'Utiliser la somme des angles d’un triangle.', 'La somme des angles intérieurs de tout triangle vaut 180°.', 'Angle inconnu', 'Soustrais de 180° la somme des deux angles connus.', 'Triangle isocèle', 'Les deux angles à la base d’un triangle isocèle ont la même mesure.'),
 ('Symétrie centrale', 'Construire l’image d’un point et d’une figure.', 'Dans une symétrie de centre O, O est le milieu du segment reliant un point et son image.', 'Coordonnées', 'Une symétrie de centre O(0 ; 0) transforme (x ; y) en (−x ; −y).', 'Conservation', 'Une symétrie centrale conserve longueurs, angles et alignements.'),
 ('Parallélogrammes', 'Reconnaître et utiliser les propriétés du parallélogramme.', 'Un parallélogramme a ses côtés opposés parallèles deux à deux.', 'Côtés', 'Ses côtés opposés sont de même longueur.', 'Diagonales', 'Ses diagonales se coupent en leur milieu.'),
 ('Aires et volumes composés', 'Calculer des aires de triangles et des volumes de pavés.', 'Une figure complexe peut être décomposée en figures simples.', 'Aire du triangle', 'Aire = base × hauteur / 2.', 'Volume du pavé', 'Volume = longueur × largeur × hauteur.'),
 ('Probabilités et statistiques', 'Calculer des probabilités simples et des moyennes.', 'Une probabilité est comprise entre 0 et 1.', 'Équiprobabilité', 'Probabilité = nombre de cas favorables / nombre de cas possibles.', 'Moyenne', 'Additionne les données puis divise par leur nombre.'),
]
SCI_6 = [
 ('Solides, liquides et gaz', 'Distinguer les trois états de la matière.', 'Un solide a une forme propre ; un liquide prend la forme du récipient ; un gaz occupe tout l’espace disponible.', 'Formes et volumes', 'Un liquide possède un volume propre mais pas de forme propre.', 'Gaz et récipient', 'Un gaz peut être comprimé et se répartit dans tout son récipient.'),
 ('La matière à l’échelle des particules', 'Comprendre que la matière est constituée de particules.', 'Dans un solide, les particules sont très proches et liées ; dans un gaz, elles sont très espacées.', 'Dans un liquide', 'Les particules restent proches tout en se déplaçant les unes par rapport aux autres.', 'Attention', 'Lors d’un changement d’état d’un corps pur, les particules ne disparaissent pas.'),
 ('Fusion, solidification et évaporation', 'Reconnaître les changements d’état de l’eau.', 'La fusion transforme un solide en liquide ; la solidification réalise l’inverse.', 'Vaporisation', 'La vaporisation transforme un liquide en gaz.', 'Condensation', 'La liquéfaction transforme un gaz en liquide.'),
 ('Mélanges homogènes et hétérogènes', 'Observer et décrire des mélanges.', 'Un mélange homogène paraît uniforme à l’œil nu ; un mélange hétérogène présente plusieurs constituants visibles.', 'Exemples', 'L’eau et l’huile forment généralement un mélange hétérogène.', 'Séparation', 'La décantation permet de séparer certains mélanges hétérogènes.'),
 ('Dissolution dans l’eau', 'Comprendre la dissolution et la solubilité.', 'Lorsqu’on dissout du sel dans l’eau, il est toujours présent même s’il n’est plus visible.', 'Vocabulaire', 'Le soluté se dissout dans le solvant pour former une solution.', 'Saturation', 'Au-delà d’une certaine quantité, un soluté ne peut plus se dissoudre dans un volume donné.'),
 ('Masse et volume', 'Mesurer et distinguer masse et volume.', 'Une balance mesure la masse ; une éprouvette graduée permet de mesurer le volume d’un liquide.', 'Unités', 'La masse peut se mesurer en g ou kg ; le volume en mL, L ou cm³.', 'Conversion', 'Un litre correspond à mille millilitres.'),
 ('Décrire un mouvement', 'Utiliser trajectoire et vitesse pour décrire un mouvement.', 'La trajectoire est l’ensemble des positions successives d’un objet.', 'Trajectoires', 'La trajectoire peut être rectiligne, circulaire ou curviligne.', 'Mouvement', 'Un mouvement est uniforme lorsque la vitesse reste constante.'),
 ('Sources et transformations d’énergie', 'Identifier des sources et formes d’énergie.', 'Une lampe électrique transforme de l’énergie électrique en énergie lumineuse et thermique.', 'Énergie mécanique', 'Un objet en mouvement possède de l’énergie cinétique.', 'Transfert', 'Un appareil reçoit de l’énergie et en transfère ou convertit une partie.'),
 ('Premiers circuits électriques', 'Reconnaître les éléments d’un circuit électrique simple.', 'Une pile peut alimenter une lampe lorsque le circuit est fermé.', 'Circuit ouvert', 'Un interrupteur ouvert empêche le courant de circuler dans un circuit simple.', 'Sécurité', 'On ne relie jamais directement les deux bornes d’une pile par un fil.'),
 ('Lumière, ombres et sources', 'Reconnaître les sources lumineuses et expliquer les ombres.', 'Une source primaire produit sa propre lumière ; un objet éclairé diffuse celle qu’il reçoit.', 'Ombre', 'Un objet opaque placé entre la source et l’écran peut former une ombre.', 'Propagation', 'Dans un milieu homogène et transparent, la lumière se propage en ligne droite.'),
]
SCI_5 = [
 ('Séparer les mélanges', 'Choisir une technique de séparation adaptée.', 'La filtration retient des particules solides en suspension dans un liquide.', 'Décantation', 'On laisse reposer pour séparer certains mélanges hétérogènes.', 'Évaporation', 'L’évaporation du solvant peut permettre de récupérer un soluté solide dissous.'),
 ('Masse, volume et masse volumique', 'Comparer des objets selon leur masse et leur volume.', 'La masse volumique est la masse d’un objet divisée par son volume.', 'Relation', 'ρ = m / V, avec des unités cohérentes.', 'Comparaison', 'À volume égal, l’objet le plus massif a la masse volumique la plus grande.'),
 ('L’air et les gaz', 'Comprendre les propriétés simples des gaz.', 'L’air est un mélange de plusieurs gaz, principalement diazote et dioxygène.', 'Gaz', 'Un gaz occupe tout le volume du récipient qui le contient.', 'Pression', 'En diminuant le volume d’un gaz enfermé, sa pression peut augmenter.'),
 ('Transformations physiques et chimiques', 'Distinguer une transformation physique d’une transformation chimique.', 'Une transformation physique ne crée pas de nouvelle espèce chimique, contrairement à une transformation chimique.', 'Exemple physique', 'La fusion de la glace est un changement d’état.', 'Indices', 'L’apparition d’un gaz ou d’un précipité peut indiquer une transformation chimique.'),
 ('Trajectoires et vitesses', 'Décrire un mouvement avec des mesures.', 'La vitesse moyenne est le quotient de la distance parcourue par la durée du trajet.', 'Relation', 'v = d / t.', 'Unités', 'Pour obtenir une vitesse en km/h, prends la distance en km et le temps en heures.'),
 ('Circuits en série et dérivation', 'Comparer les branches des circuits.', 'Dans un circuit en série, tous les dipôles appartiennent à la même boucle.', 'Série', 'Si un composant est retiré, tout le circuit en série s’ouvre.', 'Dérivation', 'Un circuit en dérivation possède plusieurs branches.'),
 ('Mesurer la tension et l’intensité', 'Identifier les appareils de mesure électriques.', 'Un ampèremètre mesure l’intensité du courant et se branche en série.', 'Voltmètre', 'Le voltmètre mesure la tension et se branche en dérivation aux bornes du dipôle.', 'Unités', 'L’intensité se mesure en ampères (A) ; la tension en volts (V).'),
 ('Conversions et transferts d’énergie', 'Décrire la chaîne énergétique d’un dispositif.', 'L’énergie ne disparaît pas lors d’une conversion : elle change de forme ou est transférée.', 'Exemple', 'Un moteur électrique convertit de l’énergie électrique en énergie mécanique et thermique.', 'Rendement', 'Une partie de l’énergie reçue peut être dissipée sous forme thermique.'),
 ('Propagation de la lumière', 'Étudier la propagation de la lumière et les matériaux.', 'Dans un milieu homogène et transparent, la lumière se propage en ligne droite.', 'Milieux', 'Un milieu opaque ne laisse pas traverser la lumière visible.', 'Vision', 'On voit un objet lorsqu’une partie de la lumière qui en provient entre dans l’œil.'),
 ('Sons et vibrations', 'Comprendre l’émission et la propagation des sons.', 'Un son est produit par une vibration qui se propage dans un milieu matériel.', 'Fréquence', 'La fréquence d’un son se mesure en hertz (Hz).', 'Vide', 'Le son ne se propage pas dans le vide.'),
]

SUBJECTS = {'mathematiques': {'name':'Mathématiques','emoji':'📐','description':'Cours et exercices de mathématiques du collège.'}, 'physique-chimie': {'name':'Physique-Chimie','emoji':'⚛️','description':'Sciences et technologie en 6e ; physique-chimie en 5e, 4e et 3e.'}}

def blocks(*parts):
    return PREFIX + json.dumps(parts, ensure_ascii=False)

def question(title, statement, answer, correction, hint1, hint2, difficulty=1, options=None, method=None, diagram=None):
    return {'title': title, 'statement': statement, 'exercise_type': 'mcq' if options else 'text', 'options': options or [], 'correct_answer': str(answer), 'correction': correction, 'hints': [hint1,hint2], 'steps':[correction], 'method': method or 'Repère les données de cet exercice, applique la propriété correspondante, puis vérifie les unités et le résultat.', 'diagram': diagram, 'difficulty': difficulty, 'points':10}

def exercise_from_math(topic, slot, level):
    # 4 familles de problèmes × 3 jeux de données : 12 exercices par chapitre.
    n = slot % 3
    kind = slot // 3
    diff = 1 if kind == 0 else 2 if kind in (1,2) else 3
    a = [6,9,12][n]; b = [4,7,8][n]; c = [2,3,5][n]
    common = 'Vérifie que le résultat est cohérent avec les valeurs de l’énoncé.'
    q = None
    if topic == 0:  # 6e decimal
        if kind == 0:
            x=f'{a},{c}'; y=f'{a},{b}'; q=(f'Lequel est le plus grand : {x} ou {y} ?', y, f'Les parties entières sont égales à {a}. Compare les dixièmes : {b} > {c}, donc {y} > {x}.', f'Les deux nombres commencent par {a} : compare leurs chiffres après la virgule.', f'Au rang des dixièmes, compare {c} et {b}.', [x,y,'Ils sont égaux'])
        elif kind == 1:
            x=a*10+c; q=(f'Quel est le chiffre des dixièmes de {a},{c}{b} ?', str(c), f'Dans {a},{c}{b}, le premier chiffre après la virgule est {c} : c’est celui des dixièmes.', 'Le chiffre des dixièmes est immédiatement à droite de la virgule.', f'Dans {a},{c}{b}, regarde le {c}, pas le {b}.', [str(c),str(b),str(a)])
        elif kind == 2:
            q=(f'Encadre {a},{c} entre deux entiers consécutifs : quel est le plus petit entier ?', str(a), f'{a} < {a},{c} < {a+1}. Le plus petit entier de l’encadrement est {a}.', f'Compare {a},{c} avec {a} puis avec {a+1}.', 'L’entier inférieur est la partie entière du nombre décimal.', [str(a),str(a+1),str(a-1)])
        else:
            x=f'{a},{b}{c}'; y=f'{a},{b}{c+2}'; q=(f'Entre {x} et {y}, quel nombre est le plus petit ?',x,f'Les dixièmes valent {b} des deux côtés ; au rang des centièmes, {c} < {c+2}, donc {x} < {y}.',f'Les deux nombres commencent par {a},{b} : cherche le premier chiffre différent.', f'Compare ensuite les centièmes {c} et {c+2}.',[x,y,f'{a},{b}{c+1}'])
    elif topic in (1,):
        if kind==0: q=(f'Calcule {a}+{b}.',str(a+b),f'{a}+{b}={a+b}.',f'Pars de {a} et ajoute {b} unités.',f'Vérifie en effectuant {a+b}−{b}.',None)
        elif kind==1: q=(f'Calcule {a*10+b}−{a}.',str(a*9+b),f'{a*10+b}−{a}={a*9+b}.',f'Soustrais {a} du nombre {a*10+b}.','Aligne les unités avant de soustraire.',None)
        elif kind==2: q=(f'Un carnet coûte {a} € et un stylo {b} €. Combien coûtent les deux articles ?',str(a+b),f'{a}+{b}={a+b} €.', 'Il faut réunir les prix des deux articles.', f'Additionne {a} et {b} en conservant l’unité euro.',None)
        else: q=(f'Un élève possède {a*10+b} billes et en donne {a+b}. Combien lui en reste-t-il ?',str(a*9),f'{a*10+b}−({a}+{b})={a*9} billes.', 'Cherche combien de billes sont données au total.', f'Soustrais {a+b} à {a*10+b}.',None)
    elif topic==2:
        if kind==0: q=(f'Calcule {a}×{b}.',str(a*b),f'{a}×{b}={a*b}.',f'Il y a {b} groupes contenant chacun {a} unités.',f'Additionne {a} exactement {b} fois.',None)
        elif kind==1: q=(f'Calcule {a*b}÷{b}.',str(a),f'{a*b}÷{b}={a}, car {a}×{b}={a*b}.', f'Cherche le nombre qui, multiplié par {b}, donne {a*b}.', f'Teste {a}×{b}.',None)
        elif kind==2: q=(f'On range {a*b} livres dans {a} cartons identiques. Combien de livres par carton ?',str(b),f'{a*b}÷{a}={b} livres.',f'Il s’agit de répartir {a*b} livres en {a} parts égales.',f'Quelle multiplication par {a} donne {a*b} ?',None)
        else: q=(f'Une salle compte {a} rangées de {b} sièges. {c} sièges restent inoccupés. Combien de personnes sont assises ?',str(a*b-c),f'{a}×{b}−{c}={a*b-c}.',f'Calcule d’abord le nombre total de sièges : {a} rangées de {b}.',f'Enlève ensuite les {c} sièges vides.',None)
    elif topic==3:
        total=a*b
        if kind==0: q=(f'Un gâteau est découpé en {b} parts égales. On en mange {c}. Quelle fraction du gâteau a été mangée ?',f'{c}/{b}',f'{c} parts sur {b} donnent la fraction {c}/{b}.', 'Le dénominateur correspond au nombre total de parts égales.', f'Place {c} au numérateur et {b} au dénominateur.',None)
        elif kind==1: q=(f'Calcule 1/{b} de {total}.',str(a),f'{total}÷{b}={a}.', f'Une part sur {b} : partage {total} par {b}.',f'Calcule {total}÷{b}.',None)
        elif kind==2: q=(f'Un club compte {total} adhérents. {c}/{b} font du tennis. Combien cela représente-t-il de personnes ?',str(a*c),f'{total}÷{b}×{c}={a*c} personnes.', f'Commence par calculer 1/{b} de {total}.', f'Multiplie ensuite les {a} adhérents par {c}.',None)
        else: q=(f'Quelle fraction est égale à {c}/{b} ?',f'{c*2}/{b*2}',f'On multiplie numérateur et dénominateur de {c}/{b} par 2 : {c*2}/{b*2}.', 'Une fraction équivalente ne change pas la valeur du partage.', 'Multiplie les deux nombres de la fraction par 2.', [f'{c*2}/{b*2}',f'{c}/{b*2}',f'{c*2}/{b}'])
    elif topic==4:
        if kind==0: q=(f'{a} cahiers coûtent {a*b} €. Quel est le prix d’un cahier ?',str(b),f'{a*b}÷{a}={b} € par cahier.', f'Le prix est proportionnel au nombre de cahiers.', f'Calcule le prix de 1 cahier en divisant {a*b} par {a}.',None)
        elif kind==1: q=(f'{a} cahiers coûtent {a*b} €. Combien coûtent {a*2} cahiers ?',str(a*b*2),f'Le nombre de cahiers double : {a*b}×2={a*b*2} €.', f'Compare les quantités de cahiers : on passe de {a} à {a*2}.', 'Quand la quantité double, le prix proportionnel double aussi.',None)
        elif kind==2: q=(f'Une recette pour {a} personnes demande {a*c} g de farine. Quelle masse faut-il pour {a*3} personnes (en g) ?',str(a*c*3),f'{a*c}×3={a*c*3} g : il faut trois fois plus de farine.',f'La recette passe de {a} à {a*3} personnes.', 'Multiplie la masse de farine par 3.',None)
        else: q=(f'Un magasin vend {b} stylos pour {a*b} €. Combien coûtent {b*3} stylos au même tarif ?',str(a*b*3),f'{a*b}×3={a*b*3} €.', f'Compare {b} stylos et {b*3} stylos.', f'Le prix est multiplié par le même facteur, ici 3.',None)
    elif topic==5:
        val=a*10
        pct=[50,25,10][n]
        val= a*20 if pct==25 else a*10
        if kind==0: q=(f'Calcule {pct} % de {val}.',str(val*pct//100),f'{pct} % de {val} = {val}×{pct}/100 = {val*pct//100}.', f'{pct} % correspond à une fraction de la quantité {val}.',f'Écris le calcul {val}×{pct}/100.',None)
        elif kind==1: q=(f'Une classe compte {a*4} élèves. La moitié vient à pied. Combien d’élèves viennent à pied ?',str(a*2),f'La moitié de {a*4} vaut {a*4}÷2={a*2}.', 'La moitié correspond à 50 %.', f'Divise {a*4} par 2.',None)
        elif kind==2: q=(f'Une école a {a*20} livres, dont 25 % sont des romans. Combien de romans ?',str(a*5),f'Un quart de {a*20} : {a*20}÷4={a*5}.', '25 % d’une quantité correspond à un quart.', f'Partage {a*20} livres en quatre groupes égaux.',None)
        else: q=(f'Sur {a*10} graines, 10 % ne germent pas. Combien de graines germent ?',str(a*9),f'10 % de {a*10} vaut {a}. Il reste {a*10}−{a}={a*9} graines.', f'Commence par calculer 10 % de {a*10}.', f'Soustrais les {a} graines qui ne germent pas.',None)
    elif topic in (6,7):
        from_u,to_u,coef=('m','cm',100) if topic==6 else ('kg','g',1000)
        if kind==0: q=(f'Convertis {a} {from_u} en {to_u}.',str(a*coef),f'{a}×{coef}={a*coef} {to_u}.', f'Un {from_u} contient {coef} {to_u}.',f'Multiplie {a} par {coef}.',None)
        elif kind==1: q=(f'Convertis {a*coef} {to_u} en {from_u}.',str(a),f'{a*coef}÷{coef}={a} {from_u}.',f'Pour passer des {to_u} aux {from_u}, il faut diviser.',f'Divise {a*coef} par {coef}.',None)
        elif kind==2: q=(f'Un objet a une {"longueur" if topic==6 else "masse"} de {a} {from_u} et un autre de {b*coef} {to_u}. Quelle est leur {"longueur" if topic==6 else "masse"} totale en {to_u} ?',str(a*coef+b*coef),f'{a} {from_u}={a*coef} {to_u}; total {(a+b)*coef} {to_u}.',f'Convertis d’abord {a} {from_u} en {to_u}.',f'Additionne {a*coef} et {b*coef}.',None)
        else: q=(f'Un colis contient {a} {from_u}. On retire {b*coef} {to_u}. Combien reste-t-il en {to_u} ?',str((a-b)*coef),f'{a} {from_u}={a*coef} {to_u}, donc {a*coef}−{b*coef}={(a-b)*coef} {to_u}.',f'Il faut soustraire deux masses/longueurs dans la même unité : {to_u}.',f'Convertis {a} {from_u} en {to_u}, puis retire {b*coef}.',None)
    elif topic==8:
        if kind==0: q=(f'Combien de minutes représentent {a} heures ?',str(a*60),f'{a}×60={a*60} minutes.', 'Une heure dure 60 minutes.',f'Multiplie {a} par 60.',None)
        elif kind==1: q=(f'Combien d’heures représentent {a*60} minutes ?',str(a),f'{a*60}÷60={a} heures.', 'Il faut faire des groupes de 60 minutes.', f'Divise {a*60} par 60.',None)
        elif kind==2: q=(f'Un film dure {a} h {b*5} min. Quelle est sa durée totale en minutes ?',str(a*60+b*5),f'{a}×60+{b*5}={a*60+b*5} minutes.',f'Convertis séparément les {a} heures en minutes.',f'Ajoute ensuite les {b*5} minutes restantes.',None)
        else: q=(f'Un trajet commence à 9 h {b*5:02d} et dure {a*5} minutes. Combien de minutes après 9 h se termine-t-il ?',str(b*5+a*5),f'{b*5}+{a*5}={(a+b)*5} min après 9 h.',f'Il s’écoule déjà {b*5} min après 9 h au départ.',f'Ajoute la durée {a*5} min.',None)
    elif topic in (9,10,11):
        if topic==9:
            if kind==0: q=(f'Quel est le périmètre (en cm) d’un carré de côté {a} cm ?',str(4*a),f'P=4×{a}={4*a} cm.', 'Un carré possède quatre côtés égaux.',f'Additionne quatre fois {a}.',None)
            elif kind==1: q=(f'Quel est le périmètre (en cm) d’un rectangle de longueur {a} cm et largeur {b} cm ?',str(2*(a+b)),f'P=2×({a}+{b})={2*(a+b)} cm.', 'Le rectangle a deux longueurs et deux largeurs.', f'Écris 2×({a}+{b}).',None)
            elif kind==2: q=(f'Un carré a pour périmètre {a*4} cm. Combien mesure un côté (en cm) ?',str(a),f'{a*4}÷4={a} cm.', 'Les quatre côtés du carré sont égaux.',f'Divise le périmètre {a*4} par 4.',None)
            else: q=(f'Une parcelle rectangulaire mesure {a} m sur {b} m. On laisse une ouverture de {c} m sans clôture. Quelle longueur de clôture faut-il (en m) ?',str(2*(a+b)-c),f'2×({a}+{b})−{c}={2*(a+b)-c} m.', 'Calcule d’abord le contour entier de la parcelle.', f'Enlève les {c} m d’ouverture.',None)
        elif topic==10:
            if kind==0: q=(f'Calcule l’aire (en cm²) d’un carré de côté {a} cm.',str(a*a),f'A={a}×{a}={a*a} cm².', 'L’aire d’un carré est côté multiplié par côté.', f'Effectue {a}×{a}.',None)
            elif kind==1: q=(f'Calcule l’aire (en cm²) d’un rectangle de longueur {a} cm et largeur {b} cm.',str(a*b),f'A={a}×{b}={a*b} cm².', 'Multiplie la longueur par la largeur.', f'Calcule {a}×{b}.',None)
            elif kind==2: q=(f'Un rectangle a une aire de {a*b} cm² et une largeur de {b} cm. Calcule sa longueur (en cm).',str(a),f'L={a*b}÷{b}={a} cm.', 'L’aire est le produit longueur × largeur.',f'Pour retrouver la longueur, divise {a*b} par {b}.',None)
            else: q=(f'Une pièce mesure {a} m sur {b} m. On retire un coin carré de côté {c} m. Quelle aire reste-t-il (en m²) ?',str(a*b-c*c),f'{a}×{b}−{c}×{c}={a*b-c*c} m².', 'Calcule séparément les aires du grand rectangle et du petit carré.',f'Soustrais {c*c} à {a*b}.',None)
        else:
            if kind==0: q=(f'Quel est le volume (en cm³) d’un cube de côté {a} cm ?',str(a**3),f'V={a}×{a}×{a}={a**3} cm³.', 'Pour un cube, multiplie les trois arêtes égales.',f'Effectue {a}×{a}×{a}.',None)
            elif kind==1: q=(f'Quel est le volume (en cm³) d’un pavé droit de dimensions {a} cm, {b} cm et {c} cm ?',str(a*b*c),f'V={a}×{b}×{c}={a*b*c} cm³.', 'Volume = longueur × largeur × hauteur.',f'Multiplie les trois dimensions {a}, {b} et {c}.',None)
            elif kind==2: q=(f'Un pavé a un volume de {a*b*c} cm³, une longueur de {a} cm et une largeur de {b} cm. Quelle est sa hauteur (en cm) ?',str(c),f'h={a*b*c}÷({a}×{b})={c} cm.', 'La hauteur est le volume divisé par l’aire de la base.',f'L’aire de la base est {a}×{b}={a*b}.',None)
            else: q=(f'Une boîte mesure {a} cm sur {b} cm sur {c} cm. Quelle est la somme des volumes de deux boîtes identiques (en cm³) ?',str(2*a*b*c),f'2×{a}×{b}×{c}={2*a*b*c} cm³.', 'Calcule le volume d’une boîte avant celui des deux.', 'Multiplie le volume de la boîte par 2.',None)
    elif topic==12:
        if kind==0: q=(f'Un angle mesure {a*5}°. Est-il aigu, droit ou obtus ?', 'Aigu',f'{a*5}° < 90° : l’angle est aigu.', 'Un angle aigu mesure strictement moins de 90°.',f'Compare {a*5}° à 90°.', ['Aigu','Droit','Obtus'])
        elif kind==1: q=(f'Un angle mesure {90+a*5}°. Est-il aigu, droit ou obtus ?', 'Obtus',f'90° < {90+a*5}° < 180° : il est obtus.', 'Un angle obtus mesure entre 90° et 180°.',f'Compare {90+a*5}° à 90° et 180°.', ['Aigu','Droit','Obtus'])
        elif kind==2: q=(f'Deux angles sont complémentaires. L’un mesure {a*5}°. Combien mesure l’autre (en degrés) ?',str(90-a*5),f'90−{a*5}={90-a*5}°.', 'Les deux angles complémentaires forment un total de 90°.', f'Soustrais {a*5}° de 90°.',None)
        else: q=(f'Un tour complet mesure 360°. Combien reste-t-il de degrés après avoir tourné de {a*20}° ?',str(360-a*20),f'360−{a*20}={360-a*20}°.', 'Un tour complet vaut 360°.', f'Soustrais {a*20}° à 360°.',None)
    elif topic==13:
        if kind==0: q=(f'Un triangle possède des angles de {a*5}° et {b*5}°. Combien mesure son troisième angle (en degrés) ?',str(180-a*5-b*5),f'180−{a*5}−{b*5}={180-a*5-b*5}°.', 'La somme des trois angles d’un triangle est 180°.', f'Additionne les deux angles connus : {a*5}+{b*5}, puis soustrais de 180.',None)
        elif kind==1: q=(f'Combien de côtés possède un {(["quadrilatère","pentagone","hexagone"])[n]} ?', str(4+n),f'Le polygone nommé possède {4+n} côtés.', 'Associe le nom du polygone à son nombre de côtés.', 'Compte les côtés du polygone étudié, sans les confondre avec ses diagonales.', [str(4+n),str(5+n),str(3+n)])
        elif kind==2: q=(f'Un triangle isocèle possède un angle au sommet de {a*5}°. Combien mesure chacun de ses angles à la base (en degrés) ?',f'{(180-a*5)/2:g}'.replace('.',','),f'Les deux angles à la base sont égaux : (180−{a*5})÷2={f"{(180-a*5)/2:g}".replace(".",",")}°.', 'Les deux angles à la base ont la même mesure.',f'Soustrais l’angle au sommet de 180°, puis divise par 2.',None)
        else: q=(f'Dans un rectangle de côtés {a} cm et {b} cm, combien de degrés mesure la somme de deux angles consécutifs ?', '180','Chaque angle vaut 90° ; deux angles valent 90+90=180°.', 'Un rectangle possède quatre angles droits.', 'Additionne deux angles de 90°.', ['180','90','270'])
    elif topic==14:
        if kind==0: q=(f'Quelle est la moyenne de {a}, {a+2} et {a+4} ?',str(a+2),f'({a}+{a+2}+{a+4})÷3={a+2}.', 'Une moyenne est la somme des valeurs divisée par leur nombre.', 'Il y a trois nombres dans cette liste.',None)
        elif kind==1: q=(f'Quelle est l’étendue des mesures {b}, {a}, {a+b} et {c} ?',str(a+b-c),f'Maximum {a+b}, minimum {c} : étendue={a+b}−{c}={a+b-c}.', 'L’étendue est maximum moins minimum.', f'Identifie {a+b} et {c} dans la série.',None)
        elif kind==2: q=(f'Un tableau donne {a} élèves à pied et {b} à vélo. Combien d’élèves au total ?',str(a+b),f'{a}+{b}={a+b} élèves.', 'Les deux groupes ne se chevauchent pas dans cet énoncé.',f'Additionne {a} et {b}.',None)
        else: q=(f'Une classe a relevé {a} livres lundi, {a+2} mardi et {a+4} mercredi. Combien en moyenne par jour ?',str(a+2),f'({a}+{a+2}+{a+4})÷3={a+2} livres.', 'Il faut la moyenne sur trois journées.', f'Additionne les trois relevés puis divise par 3.',None)
    elif topic == 15: # 5e relatifs comparer
        if kind==0: q=(f'Quel nombre est le plus grand : −{a} ou −{b} ?',f'-{b}',f'−{b} > −{a}, car {b} < {a} en distance à zéro.', 'Sur la droite graduée, le nombre le plus à droite est le plus grand.',f'Parmi −{a} et −{b}, celui le plus proche de zéro est le plus grand.',[f'-{b}',f'-{a}','0'])
        elif kind==1: q=(f'Quel est l’opposé de −{a} ?',str(a),f'L’opposé de −{a} est +{a}.', 'L’opposé a la même distance à zéro, avec le signe inverse.', f'Change uniquement le signe de −{a}.',None)
        elif kind==2: q=(f'Il fait −{a} °C, puis la température augmente de {b} °C. Quelle est la nouvelle température ?',str(b-a),f'−{a}+{b}={b-a} °C.', 'Une hausse de température s’ajoute à la température initiale.', f'Calcule −{a}+{b}.',None)
        else: q=(f'Quel est le plus petit parmi −{a}, −{b}, +{c} ?',f'-{a}',f'−{a} est inférieur à −{b} et à +{c}.', 'Un nombre négatif est inférieur à un nombre positif.',f'Entre −{a} et −{b}, celui le plus loin de zéro est le plus petit.',[f'-{a}',f'-{b}',f'+{c}'])
    elif topic==16:
        if kind==0: q=(f'Calcule (−{a})+(−{b}).',str(-a-b),f'On additionne les distances : −({a}+{b})={-a-b}.', 'Les deux termes sont négatifs.', f'Additionne {a} et {b}, puis conserve le signe −.',None)
        elif kind==1: q=(f'Calcule (−{a})+{b}.',str(b-a),f'Les signes diffèrent : −{a}+{b}={b-a}.', f'Compare les distances {a} et {b} à zéro.', 'Soustrais la plus petite distance à la plus grande et garde le signe dominant.',None)
        elif kind==2: q=(f'Calcule {a}−(−{b}).',str(a+b),f'Soustraire −{b}, c’est ajouter {b} : {a}+{b}={a+b}.', 'Soustraire un nombre revient à additionner son opposé.',f'Change −(−{b}) en +{b}.',None)
        else: q=(f'Un plongeur est à −{a} m et remonte de {b} m, puis redescend de {c} m. À quelle altitude relative est-il ?',str(-a+b-c),f'−{a}+{b}−{c}={-a+b-c} m.', f'Commence à −{a}, puis ajoute {b} car il remonte.', f'Retire enfin {c} m pour la descente.',None)
    elif topic==17:
        if kind==0: q=(f'Quelle fraction est la plus grande : {a}/{a*b} ou {b}/{a*b} ?',f'{a}/{a*b}',f'Le dénominateur est commun et {a}>{b}.', 'Avec un dénominateur commun positif, compare les numérateurs.', f'Compare {a} et {b}.',[f'{a}/{a*b}',f'{b}/{a*b}','Égalité'])
        elif kind==1: q=(f'Simplifie la fraction {a*c}/{b*c} en divisant les deux termes par {c}.',f'{a}/{b}',f'{a*c}÷{c}={a} et {b*c}÷{c}={b}.', 'On divise le numérateur et le dénominateur par le même nombre.',f'Divise chacun par {c}.',None)
        elif kind==2: q=(f'Quelle fraction est équivalente à {a}/{b} ?',f'{a*2}/{b*2}',f'On multiplie numérateur et dénominateur par 2.', 'Pour garder la même valeur, multiplie les deux termes par le même facteur.',f'Fais ×2 en haut et ×2 en bas.',[f'{a*2}/{b*2}',f'{a}/{b*2}',f'{a*2}/{b}'])
        else: q=(f'Compare {c}/{a} et {b}/{a} : écris la plus petite fraction.',f'{c}/{a}',f'Même dénominateur {a} et {c}<{b}, donc {c}/{a} est la plus petite.', 'Les deux fractions ont le même dénominateur.', f'Compare les numérateurs {c} et {b}.',None)
    elif topic==18:
        denom=a+b
        if kind==0: q=(f'Calcule {a}/{denom} + {b}/{denom} et simplifie le résultat.', '1',f'({a}+{b})/{denom}={a+b}/{denom}=1.', 'Les dénominateurs sont identiques.', f'Additionne {a} et {b} au numérateur sans modifier {denom}.',None)
        elif kind==1: q=(f'Calcule {a+b}/{denom} − {b}/{denom}.',f'{a}/{denom}',f'({a+b}−{b})/{denom}={a}/{denom}.', 'Les dénominateurs sont déjà égaux.',f'Soustrais {b} de {a+b} au numérateur.',None)
        elif kind==2: q=(f'Calcule 1/{b} + 1/{a} et donne une fraction de dénominateur {a*b}.',f'{a+b}/{a*b}',f'1/{b}={a}/{a*b} et 1/{a}={b}/{a*b}, donc ({a}+{b})/{a*b}={a+b}/{a*b}.', f'Le dénominateur commun demandé est {a*b}.', f'Réécris 1/{b} et 1/{a} avec ce dénominateur avant d’additionner.',None)
        else: q=(f'Il reste {a}/{a+b} d’un gâteau. On en mange encore {c}/{a+b}. Quelle fraction du gâteau reste ?',f'{a-c}/{a+b}',f'{a}/{a+b}−{c}/{a+b}={a-c}/{a+b}.', 'Soustrais deux fractions avec le même dénominateur.',f'Calcule {a}−{c} au numérateur et conserve {a+b} au dénominateur.',None)
    elif topic==19:
        if kind==0: q=(f'Calcule ({a}/{b})×({b}/{c}). Donne une fraction irréductible (ou un entier).', (str(a//math.gcd(a,c)) if c//math.gcd(a,c)==1 else f'{a//math.gcd(a,c)}/{c//math.gcd(a,c)}'),f'({a}×{b})/({b}×{c})={a}/{c}, puis on simplifie par {math.gcd(a,c)}.', 'Multiplie les numérateurs et les dénominateurs.', f'Le facteur {b} se simplifie entre le haut et le bas.',None)
        elif kind==1: q=(f'Calcule ({c}/{b})×{b}.',str(c),f'({c}/{b})×{b}={c}.', f'Écris {b} sous forme de fraction {b}/1.',f'Simplifie le facteur {b} au numérateur et au dénominateur.',None)
        elif kind==2: q=(f'Quel est l’inverse de la fraction {a}/{b} ?',f'{b}/{a}', f'L’inverse de {a}/{b} est {b}/{a}, leur produit vaut 1.', 'Pour l’inverse, échange numérateur et dénominateur.', f'Place {b} au numérateur et {a} au dénominateur.',None)
        else: q=(f'Un jardin mesure {a*b} m². On plante {c}/{b} de sa surface. Combien de m² sont plantés ?',str(a*c),f'{a*b}×{c}/{b}={a*c} m².', f'Calcule d’abord 1/{b} de {a*b} m².', f'Multiplie ensuite le résultat {a} par {c}.',None)
    elif topic==20:
        if kind==0: q=(f'Calcule {a}+{b}×{c}.',str(a+b*c),f'Multiplication d’abord : {b}×{c}={b*c}, puis {a}+{b*c}={a+b*c}.', 'Sans parenthèses, la multiplication est prioritaire.', f'Calcule {b}×{c} avant d’ajouter {a}.',None)
        elif kind==1: q=(f'Calcule ({a}+{b})×{c}.',str((a+b)*c),f'({a}+{b})×{c}={(a+b)*c}.', 'Commence par les parenthèses.',f'Additionne {a} et {b} avant de multiplier par {c}.',None)
        elif kind==2: q=(f'Calcule {a*b}÷{b}+{c}×{a}.',str(a+c*a),f'{a*b}÷{b}={a}; {c}×{a}={c*a}; total={a+c*a}.', 'Effectue la division et la multiplication avant l’addition.',f'Calcule d’abord {a*b}÷{b} et {c}×{a}.',None)
        else: q=(f'Calcule {a}×({b}+{c})−{b}.',str(a*(b+c)-b),f'{b}+{c}={b+c}; {a}×{b+c}={a*(b+c)}; −{b} donne {a*(b+c)-b}.', f'Calcule d’abord {b}+{c} dans les parenthèses.',f'Multiplie par {a}, puis soustrais {b}.',None)
    elif topic==21:
        if kind==0: q=(f'Réduis  {a}x + {b}x. Quel est le coefficient devant x ?',str(a+b),f'{a}x+{b}x=({a}+{b})x={a+b}x.', 'Les deux termes contiennent la même lettre x.',f'Additionne les coefficients {a} et {b}.',None)
        elif kind==1: q=(f'Pour x = {c}, calcule {a}x + {b}.',str(a*c+b),f'{a}×{c}+{b}={a*c+b}.', f'Remplace x par {c} dans l’expression.',f'Effectue la multiplication {a}×{c} avant l’addition.',None)
        elif kind==2: q=(f'Développe {a}(x+{b}). Quel est le terme constant du résultat ?',str(a*b),f'{a}(x+{b})={a}x+{a*b}.', 'Applique la distributivité à chacun des deux termes dans la parenthèse.',f'Le terme constant provient de {a}×{b}.',None)
        else: q=(f'On a {a} sachets contenant chacun x billes et {b} billes isolées. Combien de billes pour x = {c} ?',str(a*c+b),f'{a}×{c}+{b}={a*c+b} billes.',f'Écris d’abord le total sous la forme {a}x+{b}.',f'Remplace x par {c}, puis calcule.',None)
    elif topic==22:
        if kind==0: q=(f'Résous x + {b} = {a+b}.',str(a),f'x={a+b}−{b}={a}.', 'Pour isoler x, soustrais {b} aux deux membres.', f'Calcule {a+b}−{b}.',None)
        elif kind==1: q=(f'Résous {c}x = {a*c}.',str(a),f'x={a*c}÷{c}={a}.', 'Divise les deux membres de l’équation par le coefficient de x.', f'Divise {a*c} par {c}.',None)
        elif kind==2: q=(f'Résous {c}x + {b} = {a*c+b}.',str(a),f'{c}x={a*c+b}−{b}={a*c}, puis x={a*c}÷{c}={a}.', f'Soustrais {b} des deux côtés pour obtenir {c}x.', f'Divise ensuite les deux membres par {c}.',None)
        else: q=(f'Le triple d’un nombre augmenté de {b} vaut {a*3+b}. Quel est ce nombre ?',str(a),f'3x+{b}={a*3+b}; 3x={a*3}; x={a}.', 'Traduis la phrase par l’égalité 3x+{b}={a*3+b}.', f'Isole 3x, puis divise par 3.',None)
    elif topic==23:
        if kind==0: q=(f'Un cycliste parcourt {a*b} km en {a} h. Calcule sa vitesse moyenne (en km/h).',str(b),f'v=d/t={a*b}/{a}={b} km/h.', 'La vitesse moyenne est distance divisée par durée.', f'Divise {a*b} km par {a} h.',None)
        elif kind==1: q=(f'Un train roule à {a*10} km/h pendant {b} h. Calcule la distance parcourue (en km).',str(a*10*b),f'd=v×t={a*10}×{b}={a*10*b} km.', 'La distance est vitesse multipliée par durée.', f'Multiplie {a*10} km/h par {b} h.',None)
        elif kind==2: q=(f'Un marcheur parcourt {a*b} km à {b} km/h. Combien d’heures marche-t-il ?',str(a),f't=d/v={a*b}/{b}={a} h.', 'Pour retrouver la durée, divise la distance par la vitesse.', f'Divise {a*b} km par {b} km/h.',None)
        else: q=(f'Un véhicule parcourt {a*b} km en {a} heures puis {b*c} km en {c} heures. Calcule sa vitesse moyenne globale (en km/h).',str(b),f'd totale={a*b}+{b*c}={b*(a+c)} km ; t totale={a}+{c}={a+c} h ; v={b} km/h.', 'La vitesse moyenne totale utilise la distance totale et le temps total, pas la moyenne simple des vitesses.',f'Calcule ({a*b}+{b*c})/({a}+{c}).',None)
    elif topic==24:
        p=[10,20,25][n]; price=a*20 if p==25 else a*10
        if kind==0: q=(f'Calcule {p} % de {price} €.',str(price*p//100),f'Remise = {price}×{p}/100={price*p//100} €.', f'{p} % signifie {p} centièmes de {price} €.',f'Multiplie {price} par {p}/100.',None)
        elif kind==1: q=(f'Un article coûte {price} €. Il bénéficie d’une remise de {p} %. Quel est son nouveau prix ?',str(price-price*p//100),f'Remise={price*p//100} € ; nouveau prix={price}−{price*p//100}={price-price*p//100} €.', 'Calcule d’abord le montant en euros de la remise.', f'Soustrais la remise de {price} €.',None)
        elif kind==2: q=(f'Un club compte {a*10} membres, dont {p} % sont débutants. Combien sont débutants ?',str(a*10*p//100),f'{a*10}×{p}/100={a*10*p//100} personnes.',f'Un pourcentage est une part sur cent.', f'Calcule {p} % de {a*10}.',None)
        else: q=(f'Un produit à {price} € subit une hausse de {p} %. Quel prix final en € ?',str(price+price*p//100),f'Hausse = {price*p//100} € ; total = {price+price*p//100} €.', 'Calcule le montant de la hausse, pas seulement le pourcentage.',f'Ajoute cette hausse à {price} €.',None)
    elif topic==25:
        if kind==0: q=(f'Un triangle a deux angles de {a*5}° et {b*5}°. Quel est le troisième (en degrés) ?',str(180-(a+b)*5),f'180−{a*5}−{b*5}={180-(a+b)*5}°.', 'La somme des angles d’un triangle vaut 180°.', f'Soustrais les deux angles connus de 180°.',None)
        elif kind==1: q=(f'Un triangle isocèle possède deux angles égaux de {a*5}°. Quel est son troisième angle (en degrés) ?',str(180-2*a*5),f'180−2×{a*5}={180-2*a*5}°.', 'Les deux angles donnés sont égaux.', f'Calcule 180−{a*5}−{a*5}.',None)
        elif kind==2: q=(f'Dans un triangle rectangle, un angle aigu vaut {a*5}°. Quelle est la mesure de l’autre angle aigu (en degrés) ?',str(90-a*5),f'90−{a*5}={90-a*5}°.', 'Dans un triangle rectangle, les deux angles aigus sont complémentaires.',f'Soustrais {a*5}° de 90°.',None)
        else: q=(f'Un triangle a pour angles {a*5}°, {b*5}° et {180-(a+b)*5}°. Quelle est la somme de ces angles (en degrés) ?', '180', f'{a*5}+{b*5}+{180-(a+b)*5}=180°.', 'La somme ne dépend pas de la forme du triangle.', f'Additionne les trois mesures données.',None)
    elif topic==26:
        if kind==0: q=(f'Par la symétrie de centre O(0 ; 0), quelle est l’abscisse de l’image du point A({a} ; {b}) ?',str(-a),f'L’image de ({a} ; {b}) est (−{a} ; −{b}) ; son abscisse vaut −{a}.', 'Le centre O est le milieu entre le point et son image.', f'Change le signe de l’abscisse {a}.',None)
        elif kind==1: q=(f'Par la symétrie de centre O(0 ; 0), quelle est l’ordonnée de l’image de B(−{a} ; {b}) ?',str(-b),f'L’image de B est ({a} ; −{b}).', 'Dans la symétrie de centre origine, les deux coordonnées changent de signe.',f'Change le signe de {b}.',None)
        elif kind==2: q=(f'Le point O est le milieu du segment [AA’] de longueur {a*2} cm. Quelle est la longueur OA (en cm) ?',str(a),f'OA={a*2}÷2={a} cm.', 'Le centre de symétrie est le milieu du segment reliant les points.', f'Partage {a*2} cm en deux moitiés.',None)
        else: q=(f'Une figure possède un segment de longueur {a} cm. Combien mesure son image par symétrie centrale (en cm) ?',str(a),f'La symétrie centrale conserve les longueurs : {a} cm.', 'Une symétrie centrale ne modifie pas la taille des figures.',f'Le segment image a la même longueur que le segment initial.',None)
    elif topic==27:
        if kind==0: q=(f'Un parallélogramme a un côté AB de {a} cm. Quelle est la longueur du côté opposé CD (en cm) ?',str(a),f'Les côtés opposés sont de même longueur : CD=AB={a} cm.', 'Cherche la propriété des côtés opposés du parallélogramme.',f'CD est opposé à AB.',None)
        elif kind==1: q=(f'Une diagonale d’un parallélogramme mesure {a*2} cm. Ses diagonales se coupent en O. Quelle est la longueur de sa moitié (en cm) ?',str(a),f'{a*2}÷2={a} cm.', 'Les diagonales du parallélogramme se coupent en leur milieu.',f'Partage {a*2} cm par 2.',None)
        elif kind==2: q=(f'Un parallélogramme a deux côtés consécutifs de {a} cm et {b} cm. Calcule son périmètre (en cm).',str(2*(a+b)),f'P=2×({a}+{b})={2*(a+b)} cm.', 'Les côtés opposés ont les mêmes longueurs.',f'Additionne {a}+{b}, puis multiplie par 2.',None)
        else: q=(f'Un parallélogramme a un périmètre de {2*(a+b)} cm et un côté de {a} cm. Calcule la longueur de son côté consécutif (en cm).',str(b),f'P/2={a+b}; autre côté={a+b}−{a}={b} cm.', 'Le demi-périmètre est la somme des longueurs de deux côtés consécutifs.',f'Calcule {2*(a+b)}÷2−{a}.',None)
    elif topic==28:
        if kind==0: q=(f'Un triangle a une base de {a*2} cm et une hauteur de {b} cm. Calcule son aire (en cm²).',str(a*b),f'A=({a*2}×{b})÷2={a*b} cm².', 'L’aire d’un triangle vaut base × hauteur / 2.',f'Calcule ({a*2}×{b})÷2.',None)
        elif kind==1: q=(f'Un pavé droit mesure {a} cm × {b} cm × {c} cm. Quel est son volume (en cm³) ?',str(a*b*c),f'V={a}×{b}×{c}={a*b*c} cm³.', 'Multiplie les trois dimensions du pavé.',f'Calcule d’abord {a}×{b}, puis ×{c}.',None)
        elif kind==2: q=(f'Un rectangle mesure {a} cm sur {b} cm. On lui enlève un triangle de base {a} cm et de hauteur {b} cm. Quelle aire reste-t-il (en cm²) ?',str(a*b//2),f'A rectangle={a*b} ; triangle={a*b//2} ; aire restante={a*b//2} cm².', 'Calcule l’aire du rectangle puis celle du triangle retiré.', f'Le triangle occupe la moitié du rectangle : {a*b}÷2.',None)
        else: q=(f'Une boîte a un volume de {a*b*c} cm³ et une base de {a} cm × {b} cm. Quelle est sa hauteur (en cm) ?',str(c),f'h=V/(L×l)={a*b*c}/({a}×{b})={c} cm.', 'La hauteur se trouve en divisant le volume par l’aire de la base.',f'Calcule l’aire {a}×{b}, puis divise {a*b*c} par ce résultat.',None)
    elif topic==29:
        if kind==0: q=(f'Une urne contient {a} boules rouges et {b} boules bleues. Quelle est la probabilité de tirer une rouge (sous forme de fraction) ?',f'{a}/{a+b}',f'Cas favorables {a}, cas possibles {a+b} : {a}/{a+b}.', 'La probabilité est le nombre de boules rouges divisé par le nombre total.',f'Le nombre total de boules est {a}+{b}.',None)
        elif kind==1: q=(f'On lance un dé équilibré à 6 faces. Quelle est la probabilité d’obtenir {(["un nombre pair","un nombre strictement supérieur à 4","un multiple de 3"])[n]} (fraction non simplifiée de dénominateur 6) ?', (['3/6','2/6','2/6'])[n], (['Les issues favorables sont 2, 4, 6 : 3 chances sur 6.','Les issues favorables sont 5 et 6 : 2 chances sur 6.','Les issues favorables sont 3 et 6 : 2 chances sur 6.'])[n], 'Liste les six faces du dé : 1, 2, 3, 4, 5, 6.', 'Compte uniquement celles qui satisfont la condition, puis conserve 6 au dénominateur.',None)
        elif kind==2: q=(f'Calcule la moyenne des valeurs {a}, {a+2} et {a+4}.',str(a+2),f'({a}+{a+2}+{a+4})÷3={a+2}.', 'Additionne les trois observations.', 'Divise la somme par 3.',None)
        else: q=(f'Un sac contient {a} billes vertes et {b} billes jaunes. Quelle est la probabilité de ne PAS tirer de bille verte (fraction) ?',f'{b}/{a+b}',f'Ne pas tirer vert signifie tirer l’une des {b} billes jaunes parmi {a+b}.', 'Repère les issues contraires : seules les billes jaunes conviennent.',f'Divise {b} par le total {a+b}.',None)
    if not q:
        raise ValueError((level,topic,slot))
    st,ans,corr,h1,h2,opts=q
    # Réponses numériques libres : aucune fuite du résultat dans les indices.
    return question(f'Exercice {slot+1} — {st[:60]}',st,ans,corr,h1,h2,diff,opts,method='Écris la relation adaptée aux données de la question, effectue le calcul en respectant l’ordre des opérations, puis vérifie ton résultat.')

# Six questions conceptuelles et six applications ciblées par chapitre de sciences.
# Les applications sont déclinées en trois contextes chiffrés (indices personnalisés à l’énoncé).
SCI_SKILLS = {
 'Solides, liquides et gaz': [('Quelle est la propriété de forme d’un liquide ?','Il prend la forme du récipient.','Il garde une forme propre.','Il occupe forcément tout le volume.','Un liquide conserve son volume mais épouse la forme de son récipient.'),('Un ballon rempli d’air est placé dans une boîte vide puis percé. Dans la boîte fermée, l’air se répartit-il dans tout le volume ?','Oui.','Non.','Seulement au fond.','Un gaz tend à occuper tout l’espace disponible.'),('De la glace fond dans un verre. Dans quel état se trouve la matière après fusion ?','Liquide.','Solide.','Gazeux.','La fusion transforme le solide en liquide.'),('Quel état possède généralement une forme et un volume propres ?','Solide.','Liquide.','Gaz.','Un solide conserve sa forme sans récipient.'),('Le gaz enfermé dans une seringue est comprimé. Quel état est le plus facilement compressible ?','Gazeux.','Liquide.','Solide.','Les gaz peuvent être comprimés car leurs particules sont espacées.'),('On verse un verre d’eau dans deux récipients de formes différentes. Que conserve l’eau ?','Son volume.','Sa forme.','La forme du premier récipient.','Un liquide conserve son volume sans conserver sa forme.')],
 'La matière à l’échelle des particules': [('Dans quel état les particules sont-elles généralement les plus espacées ?','Gazeux.','Liquide.','Solide.','Les particules d’un gaz sont beaucoup plus espacées.'),('Lors d’une fusion, les particules d’eau disparaissent-elles ?','Non.','Oui.','Une sur deux.','Le changement d’état modifie leur organisation, pas leur existence.'),('Dans un solide, les particules peuvent-elles se déplacer librement les unes autour des autres ?','Non.','Oui.','Uniquement en hiver.','Les particules restent proches et liées dans un solide.'),('Un liquide coule : que peuvent faire ses particules ?','Se déplacer les unes par rapport aux autres.','Rester immobiles.','Disparaître.','Les particules du liquide restent proches mais peuvent se réorganiser.'),('Dans un gaz, le récipient est agrandi sans ajouter de matière. Que devient l’espacement moyen des particules ?','Il augmente.','Il diminue.','Il devient nul.','Le même nombre de particules occupe plus d’espace.'),('Dans un corps pur qui change d’état, les particules changent-elles d’espèce chimique ?','Non.','Oui.','Uniquement lors d’une fusion.','Un changement d’état est une transformation physique.')],
 'Fusion, solidification et évaporation': [('Comment appelle-t-on le passage du solide au liquide ?','Fusion.','Solidification.','Liquéfaction.','La fusion transforme la glace en eau liquide.'),('Comment appelle-t-on le passage du liquide au solide ?','Solidification.','Vaporisation.','Fusion.','La solidification transforme l’eau liquide en glace.'),('Du linge mouillé sèche à l’air libre. Quel changement d’état intervient ?','Vaporisation.','Fusion.','Solidification.','L’eau liquide passe progressivement à l’état gazeux.'),('De la buée apparaît sur un miroir froid. Quel changement d’état a lieu ?','Liquéfaction.','Fusion.','Sublimation.','La vapeur d’eau devient liquide au contact de la surface froide.'),('Une flaque d’eau disparaît au soleil. L’eau a-t-elle été détruite ?','Non, elle est passée dans l’air.','Oui.','Elle est devenue du sel.','L’évaporation ne fait pas disparaître la matière.'),('De l’eau gèle au congélateur. Quelle transformation est observée ?','Solidification.','Vaporisation.','Fusion.','Le liquide devient solide.')],
 'Mélanges homogènes et hétérogènes': [('Eau et huile forment deux couches visibles. Quel est le type de mélange ?','Hétérogène.','Homogène.','Corps pur.','Deux phases visibles caractérisent ici un mélange hétérogène.'),('Un sirop bien mélangé à de l’eau paraît uniforme. Quel mélange obtient-on ?','Homogène.','Hétérogène.','Corps pur.','Les constituants ne sont plus distinguables à l’œil nu.'),('Quelle technique permet de séparer l’eau et l’huile après repos ?','Décantation.','Aimantation.','Fusion.','Les phases non miscibles se séparent par décantation.'),('L’eau salée transparente est-elle toujours un mélange ?','Oui.','Non.','Seulement si on voit le sel.','Le sel dissous reste présent dans la solution.'),('Du sable est visible dans l’eau. Quel est le type de mélange ?','Hétérogène.','Homogène.','Gaz.','Le solide est visible dans le liquide.'),('Quel mélange est homogène à l’œil nu ?','Eau et sucre totalement dissous.','Eau et gravier.','Eau et huile.','La solution sucrée uniforme est homogène.')],
 'Dissolution dans l’eau': [('Dans l’eau salée, quel est le solvant ?','L’eau.','Le sel.','L’air.','Le solvant est le liquide qui dissout le soluté.'),('Dans l’eau salée, quel est le soluté ?','Le sel.','L’eau.','Le verre.','Le sel est la substance dissoute.'),('Quand le sucre n’est plus visible dans une boisson, est-il toujours présent ?','Oui.','Non.','Il s’est transformé en air.','Les particules de sucre sont dispersées dans l’eau.'),('Un dépôt de sel reste au fond malgré l’agitation. Comment appelle-t-on cet état de la solution ?','Saturée.','Vide.','Pure.','La solution a atteint sa capacité de dissolution dans ces conditions.'),('Comment peut-on récupérer le sel dissous dans l’eau ?','Par évaporation de l’eau.','Avec un aimant.','En mettant un couvercle.','Quand le solvant s’évapore, le sel solide reste.'),('Le sucre se dissout-il dans l’huile comme dans l’eau ?','Non, pas nécessairement.','Oui, toujours de la même façon.','Le sucre disparaît dans tous les liquides.','La solubilité dépend du couple soluté-solvant.')],
 'Masse et volume': [('Quel appareil permet de mesurer la masse d’un objet ?','Une balance.','Un thermomètre.','Un voltmètre.','La balance mesure une masse.'),('Quel instrument gradué permet de mesurer le volume d’un liquide ?','Une éprouvette graduée.','Un chronomètre.','Un rapporteur.','Les graduations donnent le volume de liquide.'),('Quelle grandeur s’exprime en kilogrammes ?','La masse.','Le volume.','La vitesse.','Le kilogramme est une unité de masse.'),('Quelle grandeur s’exprime en litres ?','Le volume.','La masse.','La température.','Le litre est une unité de volume.'),('Quelle quantité de matière change si l’on transvase toute l’eau d’un verre dans une carafe, sans perte ?','Ni sa masse ni son volume.','Sa masse uniquement.','Son volume uniquement.','Le changement de récipient ne modifie pas la quantité d’eau.'),('Une éprouvette contient 100 mL d’eau. On ajoute 50 mL d’eau sans perte : quel volume obtient-on ?','150 mL.','50 mL.','100 mL.','On additionne les deux volumes d’un même liquide.')],
 'Décrire un mouvement': [('Une voiture roule sur une route droite. Quelle est sa trajectoire ?','Rectiligne.','Circulaire.','Immobile.','La trajectoire suit une ligne droite.'),('Une nacelle tourne autour du centre d’une grande roue. Quelle est sa trajectoire ?','Circulaire.','Rectiligne.','Immobile.','Elle suit un cercle autour d’un centre.'),('Un objet parcourt des distances égales pendant des durées égales. Son mouvement est-il uniforme ?','Oui.','Non.','Impossible pour tout objet.','La vitesse reste constante lorsque les distances par durée sont identiques.'),('Que décrit la trajectoire d’un mobile ?','Les positions successives.','Sa couleur.','Sa masse seulement.','La trajectoire est la courbe suivie par le mobile.'),('Un vélo freine. Comment évolue sa vitesse ?','Elle diminue.','Elle augmente nécessairement.','Elle reste toujours constante.','Freiner consiste à ralentir.'),('Un objet qui tourne à vitesse constante change-t-il de direction ?','Oui.','Non.','Il reste immobile.','La direction de la vitesse change le long d’une trajectoire circulaire.')],
 'Sources et transformations d’énergie': [('Dans une lampe allumée, quelle énergie utile est produite ?','Énergie lumineuse.','Énergie chimique uniquement.','Énergie nucléaire.','La lampe convertit notamment de l’énergie électrique en lumière.'),('Quelle énergie possède un objet en mouvement ?','Énergie cinétique.','Énergie lumineuse uniquement.','Aucune énergie.','La vitesse est liée à l’énergie cinétique.'),('Quelle source alimente un panneau solaire photovoltaïque ?','La lumière du Soleil.','Le bruit du vent.','Le mouvement des roues.','Le panneau convertit l’énergie lumineuse en énergie électrique.'),('Une bouilloire chauffe l’eau. Quelle forme d’énergie reçoit principalement l’eau ?','Énergie thermique.','Énergie sonore.','Énergie lumineuse uniquement.','L’eau reçoit un transfert thermique.'),('Quel appareil transforme l’énergie électrique en énergie mécanique ?','Un moteur électrique.','Une simple règle.','Une pierre immobile.','Le moteur met un objet en mouvement.'),('Un appareil allumé chauffe aussi la pièce. Cette chaleur est-elle une forme d’énergie transférée ?','Oui.','Non.','Ce n’est pas lié à l’énergie.','Une partie de l’énergie peut être transférée sous forme thermique.')],
 'Premiers circuits électriques': [('Une lampe est reliée à une pile dans une boucle complète. Que peut-elle faire ?','S’allumer.','Devenir une pile.','Produire de l’eau.','Un circuit fermé permet le passage du courant.'),('Un interrupteur ouvert est placé en série avec une lampe. Que se passe-t-il ?','La lampe s’éteint.','La lampe brille davantage.','La pile devient un générateur infini.','L’interrupteur ouvert coupe la boucle.'),('Quel composant fournit l’énergie électrique dans un circuit simple ?','La pile.','Le fil seul.','L’interrupteur seul.','La pile joue le rôle de générateur.'),('Quelle action crée un risque de court-circuit d’une pile ?','Relier directement ses deux bornes par un fil.','Brancher une lampe correctement.','Ouvrir l’interrupteur.','La liaison directe des bornes peut provoquer un échauffement dangereux.'),('Quel composant permet d’ouvrir ou de fermer une boucle ?','Un interrupteur.','Une règle.','Un verre.','L’interrupteur contrôle la continuité électrique.'),('Un circuit n’a plus de pile. La lampe peut-elle rester alimentée par ce circuit simple ?','Non.','Oui, toujours.','Oui, si le fil est long.','Sans générateur, le circuit simple n’alimente pas la lampe.')],
 'Lumière, ombres et sources': [('Le Soleil produit-il sa propre lumière ?','Oui.','Non.','Seulement la nuit.','Le Soleil est une source primaire de lumière.'),('La Lune produit-elle la lumière visible avec laquelle on la voit ?','Non, elle réfléchit celle du Soleil.','Oui, elle est une étoile.','Elle ne reçoit aucune lumière.','La Lune diffuse la lumière solaire.'),('Quel objet forme une ombre nette lorsqu’il intercepte un faisceau ?','Un objet opaque.','Un objet parfaitement transparent.','Un miroir absent.','Un objet opaque bloque la propagation directe de la lumière.'),('Dans un milieu transparent homogène, comment la lumière se propage-t-elle ?','En ligne droite.','En spirale uniquement.','Elle reste immobile.','La propagation rectiligne explique la formation des ombres.'),('La lumière issue d’un objet doit-elle entrer dans l’œil pour qu’on le voie ?','Oui.','Non.','Seulement si l’objet est rouge.','La vision nécessite que de la lumière provenant de l’objet entre dans l’œil.'),('Un écran placé derrière un objet opaque par rapport à une lampe présente quoi ?','Une zone d’ombre.','Une lumière plus intense partout.','Un son.','L’objet intercepte une partie des rayons lumineux.')],
 'Séparer les mélanges': [('Comment séparer un mélange eau + sable sans dissoudre le sable ?','Filtration.','Fusion.','Aimantation de l’eau.','Le filtre retient les grains solides.'),('Comment séparer deux liquides non miscibles comme l’huile et l’eau ?','Décantation.','Dissolution.','Congélation forcée.','Les liquides se séparent en couches après repos.'),('Comment récupérer le sel dissous dans l’eau ?','Évaporer l’eau.','Filtrer directement les ions dissous.','Attendre que le sel flotte.','L’évaporation retire le solvant, le soluté solide reste.'),('Pourquoi un filtre à café retient-il le marc ?','Ses pores retiennent les particules solides.','Il absorbe toute la caféine.','Il transforme le solide en gaz.','La filtration sépare un solide non dissous du liquide.'),('Une eau boueuse reste au repos ; les particules tombent. Quel procédé est utilisé ?','Décantation.','Électrolyse.','Fusion.','La gravité favorise la séparation de particules en suspension.'),('L’eau salée claire peut-elle être séparée en sel et eau par filtration ordinaire ?','Non.','Oui, facilement.','Oui, si le filtre est coloré.','Le sel dissous traverse un filtre ordinaire avec le solvant.')],
 'Masse, volume et masse volumique': [('Quel appareil mesure la masse d’un échantillon ?','Une balance.','Un rapporteur.','Un voltmètre.','La masse se mesure avec une balance.'),('Quelle relation permet de calculer la masse volumique ?','Masse divisée par volume.','Masse multipliée par volume.','Volume moins masse.','ρ=m/V.'),('Deux cubes ont le même volume. Le cube A est plus massif. Lequel possède la plus grande masse volumique ?','Le cube A.','Le cube B.','Ils ont nécessairement la même.','À volume égal, ρ augmente avec la masse.'),('Quelle est l’unité possible de la masse volumique ?','g/cm³.','km/h.','V.','Une masse divisée par un volume donne une unité comme g/cm³.'),('Quelle relation donne la masse à partir de ρ et V ?','m = ρ × V.','m = ρ / V.','m = V − ρ.','On multiplie la masse volumique par le volume.'),('À masse égale, si le volume d’un objet double, que devient sa masse volumique ?','Elle est divisée par deux.','Elle double.','Elle ne change jamais.','ρ=m/V : le dénominateur double.')],
 'L’air et les gaz': [('Quel gaz est majoritaire dans l’air ?','Le diazote.','Le dioxygène.','Le dioxyde de carbone.','L’air contient principalement du diazote.'),('Quel gaz est nécessaire à la respiration humaine ?','Le dioxygène.','Le diazote uniquement.','L’hélium.','Nos cellules utilisent le dioxygène pour respirer.'),('Un gaz enfermé occupe-t-il tout le volume disponible ?','Oui.','Non.','Seulement les coins.','Un gaz se répartit dans son récipient.'),('De l’air est comprimé dans une seringue fermée. Que devient son volume ?','Il diminue.','Il augmente forcément.','Il devient infini.','Comprimer un gaz réduit le volume disponible.'),('L’air est-il un corps pur ?','Non, c’est un mélange de gaz.','Oui, uniquement du dioxygène.','Oui, uniquement du diazote.','L’air associe plusieurs espèces gazeuses.'),('À température constante, un gaz comprimé voit sa pression généralement…','Augmenter.','Diminuer jusqu’à zéro.','Ne jamais changer.','La pression peut croître lorsque le volume se réduit.')],
 'Transformations physiques et chimiques': [('La glace fond : s’agit-il d’une transformation physique ou chimique ?','Physique.','Chimique.','Nucléaire.','L’eau reste la même espèce chimique.'),('Le fer rouille : s’agit-il d’une transformation physique ou chimique ?','Chimique.','Physique.','Simple changement d’état.','De nouvelles espèces chimiques se forment.'),('Du sel se dissout sans réaction dans l’eau : quel type de changement illustre cet exemple ?','Transformation physique.','Combustion.','Transformation nucléaire.','La dissolution décrite ne forme pas de nouvelle espèce chimique.'),('Une réaction produit un gaz inédit. Peut-on suspecter une transformation chimique ?','Oui.','Non.','Jamais si la température est constante.','L’apparition d’une nouvelle espèce peut indiquer une réaction.'),('Après une réaction dans un récipient hermétiquement fermé, la masse totale est-elle conservée ?','Oui.','Non, elle disparaît.','Elle double automatiquement.','La masse totale se conserve dans un système fermé.'),('La cire d’une bougie fond avant de brûler. La fusion de la cire est…','Physique.','Chimique.','Une disparition de matière.','Fondre est un changement d’état.')],
 'Trajectoires et vitesses': [('Une voiture se déplace en ligne droite. Comment nomme-t-on sa trajectoire ?','Rectiligne.','Circulaire.','Périodique.','Les positions successives sont alignées.'),('La grande roue entraîne une nacelle autour de son centre. Quelle trajectoire ?','Circulaire.','Rectiligne.','Immobile.','La nacelle décrit un cercle.'),('Quelle relation donne la vitesse moyenne ?','Distance divisée par durée.','Durée divisée par distance.','Distance plus durée.','v=d/t.'),('Un piéton accélère sur une ligne droite. Qu’est-ce qui augmente ?','Sa vitesse.','Sa masse obligatoirement.','Son volume.','Accélérer signifie augmenter la valeur de la vitesse.'),('Quel ensemble d’unités permet un résultat en km/h ?','Distance en km et durée en h.','Distance en m et durée en s.','Distance en kg et durée en h.','Le quotient km/h exige des kilomètres et des heures.'),('Un objet parcourt 10 m chaque seconde sur une trajectoire droite. Son mouvement est-il uniforme ?','Oui.','Non.','Impossible à dire sans masse.','Une distance égale par durée égale traduit une vitesse constante.')],
 'Circuits en série et dérivation': [('Deux lampes sont dans une seule boucle. Quel montage est-ce ?','En série.','En dérivation.','Sans circuit.','Le montage en série ne comporte qu’une boucle.'),('Une lampe grille dans un montage en série de deux lampes. Que devient l’autre ?','Elle s’éteint.','Elle reste toujours allumée.','Elle double de puissance.','La boucle est interrompue.'),('Un circuit possède deux branches contenant chacune une lampe. Quel montage ?','En dérivation.','En série.','Court-circuit nécessairement.','Des branches différentes caractérisent la dérivation.'),('Dans un montage en dérivation, une branche est ouverte. Une autre branche fermée peut-elle rester alimentée ?','Oui.','Non, jamais.','Uniquement sans pile.','Chaque branche fermée peut constituer un trajet du courant.'),('Combien de boucles contient un circuit simple en série ?','Une.','Deux obligatoirement.','Aucune.','Tous les dipôles sont sur une seule boucle.'),('Un interrupteur général placé avant une séparation de branches est ouvert. Que deviennent les lampes ?','Elles s’éteignent toutes.','Elles s’allument toutes.','Une seule s’allume obligatoirement.','L’interrupteur général ouvre l’alimentation de toutes les branches.')],
 'Mesurer la tension et l’intensité': [('Quel appareil mesure une intensité électrique ?','Ampèremètre.','Voltmètre.','Thermomètre.','L’ampèremètre mesure le courant.'),('Quel appareil mesure une tension électrique ?','Voltmètre.','Ampèremètre.','Balance.','Le voltmètre mesure la tension aux bornes d’un dipôle.'),('Comment branche-t-on un ampèremètre ?','En série.','En dérivation uniquement.','Sans fil.','L’ampèremètre est traversé par le courant à mesurer.'),('Comment branche-t-on un voltmètre ?','En dérivation.','En série uniquement.','Directement à la prise secteur.','Le voltmètre se branche aux bornes du dipôle.'),('Quelle unité exprime l’intensité ?','Ampère (A).','Volt (V).','Joule (J).','L’intensité se mesure en ampères.'),('Quelle unité exprime la tension ?','Volt (V).','Ampère (A).','Kilogramme (kg).','La tension se mesure en volts.')],
 'Conversions et transferts d’énergie': [('Un moteur électrique met en mouvement une roue. Quelle forme utile reçoit la roue ?','Énergie mécanique.','Énergie nucléaire.','Énergie chimique uniquement.','Le moteur convertit l’électricité en mouvement.'),('Une lampe convertit l’énergie électrique principalement en…','Lumière et chaleur.','Masse.','Énergie cinétique seule.','La lampe émet de la lumière et chauffe.'),('L’énergie totale disparaît-elle pendant une conversion dans un système isolé ?','Non.','Oui.','Uniquement la nuit.','L’énergie se conserve : elle change de forme.'),('Quel appareil transforme de l’énergie lumineuse en énergie électrique ?','Un panneau photovoltaïque.','Un haut-parleur.','Une résistance chauffante.','Une cellule photovoltaïque convertit la lumière en électricité.'),('Un haut-parleur produit du son et chauffe légèrement. Peut-on avoir plusieurs formes d’énergie en sortie ?','Oui.','Non.','Seulement si la pièce est vide.','L’énergie peut être répartie entre plusieurs conversions.'),('Une résistance chauffante convertit principalement l’électricité en…','Énergie thermique.','Énergie lumineuse uniquement.','Énergie potentielle gravitationnelle.','Le courant entraîne un échauffement.')],
 'Propagation de la lumière': [('Dans l’air homogène, la lumière se propage comment ?','En ligne droite.','En courbes arbitraires.','Elle est immobile.','La propagation rectiligne est un modèle adapté en milieu homogène.'),('Un matériau opaque laisse-t-il passer la lumière visible ?','Non.','Oui, entièrement.','Seulement les couleurs bleues.','L’objet opaque intercepte la lumière.'),('Pour voir une pomme éclairée, que doit-il se passer ?','La lumière venant de la pomme doit entrer dans l’œil.','La pomme doit produire du son.','Il faut que la pomme soit lumineuse par elle-même.','L’objet éclairé diffuse une partie de la lumière qu’il reçoit.'),('La Lune est-elle une source primaire de lumière visible ?','Non.','Oui, comme le Soleil.','Uniquement lors d’une éclipse.','Elle réfléchit la lumière solaire.'),('Pourquoi un poteau opaque forme-t-il une ombre ?','Il intercepte une partie des rayons lumineux.','Il absorbe le son.','Il supprime la lumière partout.','L’ombre se forme dans la région où la lumière directe n’arrive pas.'),('Comment nomme-t-on un matériau qui laisse passer la lumière et permet de voir nettement à travers ?','Transparent.','Opaque.','Magnétique.','La transparence autorise le passage de la lumière et la vision nette.')],
 'Sons et vibrations': [('Quelle est l’origine physique d’un son émis par une corde de guitare ?','Une vibration.','Un courant électrique obligatoire.','Une lumière.','La corde vibrante met l’air environnant en vibration.'),('Le son peut-il se propager dans le vide ?','Non.','Oui, aussi bien que dans l’air.','Oui, uniquement la nuit.','Le son exige un milieu matériel.'),('Quelle unité est utilisée pour la fréquence d’un son ?','Hertz (Hz).','Volt (V).','Kilogramme (kg).','La fréquence se mesure en hertz.'),('Une fréquence plus élevée correspond généralement à un son…','Plus aigu.','Plus grave.','Plus faible nécessairement.','La hauteur perçue est liée à la fréquence.'),('Un haut-parleur émet un son. Qu’est-ce qui met l’air en mouvement ?','La vibration de sa membrane.','La couleur du plastique.','La lumière de l’écran.','La membrane vibrante crée une onde sonore dans l’air.'),('Que perçoit-on lorsque l’amplitude d’un son augmente, à distance comparable ?','Un son généralement plus fort.','Un son nécessairement plus aigu.','L’absence de son.','L’amplitude est liée à l’intensité sonore perçue.')],
}

def science_question(title, skill, level, index):
    prompt, ans, wrong1, wrong2, explanation = skill
    h1 = 'Dans cette situation, repère la propriété ou la grandeur qui est observée : « ' + prompt.split('?')[0][:100].rstrip('. ') + ' ».'
    h2 = 'Distingue les notions du chapitre : ' + {
        '6e': 'forme, volume, état, énergie ou trajet selon la situation.',
        '5e': 'nature de la transformation, grandeur mesurée, trajet ou transfert selon la situation.'
    }[level]  # remplacés ensuite par des indices précis par thème.
    return question(f'Exercice {index+1} — {prompt[:66]}',prompt,ans,explanation,h1,h2,1 if index<4 else 2 if index<8 else 3,[ans,wrong1,wrong2],method=explanation)

SCI_APPS = {
 'Solides, liquides et gaz': ('Un récipient contient {a} mL d’eau liquide. On la transvase sans perte dans un autre récipient. Quel volume d’eau (en mL) reste-t-il ?', lambda a,b,c:a, 'Le volume d’un liquide ne dépend pas de la forme de son récipient.', 'Aucune quantité de liquide n’a été perdue : conserve les {a} mL.'),
 'La matière à l’échelle des particules': ('Un récipient contient {a} particules d’un corps pur. Après une simple fusion sans perte, combien de particules contient-il ?',lambda a,b,c:a,'Un changement d’état conserve les particules.','Aucune particule n’a été ajoutée ou perdue : conserve le nombre initial {a}.'),
 'Fusion, solidification et évaporation': ('Un glaçon a une masse de {a} g. Il fond entièrement dans un récipient fermé, sans perte. Quelle est la masse de l’eau obtenue (en g) ?',lambda a,b,c:a,'Un changement d’état conserve la masse dans un système fermé.','Le glaçon avait une masse de {a} g et rien n’a quitté le récipient.'),
 'Mélanges homogènes et hétérogènes': ('On mélange {a} mL d’eau et {b} mL de colorant miscible ; suppose les volumes additifs. Quel volume obtient-on (en mL) ?',lambda a,b,c:a+b,'Additionne les volumes puisque l’énoncé les suppose additifs.','Calcule {a}+{b} mL.'),
 'Dissolution dans l’eau': ('On verse {a} g de sucre dans {b} g d’eau et tout se dissout sans perte. Quelle est la masse de solution (en g) ?',lambda a,b,c:a+b,'Dissoudre ne détruit pas le sucre ; la masse se conserve.','Additionne les masses de sucre {a} g et d’eau {b} g.'),
 'Masse et volume': ('Une bouteille contient {a} L d’eau. Quel volume cela représente-t-il en mL ?',lambda a,b,c: a*1000,'Un litre correspond à 1 000 mL.','Multiplie {a} par 1 000.'),
 'Décrire un mouvement': ('Un mobile parcourt {a*b} m à la vitesse constante de {b} m/s. Combien de secondes dure ce trajet ?',lambda a,b,c:a,'Pour une vitesse constante, durée = distance / vitesse.','Divise {a*b} m par {b} m/s.'),
 'Sources et transformations d’énergie': ('Un dispositif reçoit {a+b} J d’énergie ; il transfère {a} J sous forme lumineuse. Combien de joules sont transférés sous d’autres formes ?',lambda a,b,c:b,'L’énergie totale se répartit entre les différentes formes.','Soustrais {a} J de l’énergie reçue {a+b} J.'),
 'Premiers circuits électriques': ('Une pile alimente {a} lampes en série. L’interrupteur général est ouvert. Combien de lampes peuvent rester allumées dans ce circuit simple ?',lambda a,b,c:0,'L’interrupteur ouvert interrompt toute la boucle en série.','Même avec {a} lampes, la boucle est ouverte : aucune n’est alimentée.'),
 'Lumière, ombres et sources': ('Un écran reçoit la lumière de {a} lampes distinctes. On éteint {b} lampes. Combien de lampes éclairent encore l’écran ?',lambda a,b,c:a-b,'Compte les sources lumineuses encore actives.','Soustrais les {b} lampes éteintes aux {a} initiales.'),
 'Séparer les mélanges': ('On filtre un mélange contenant {a} g de sable insoluble et {b} g de sel entièrement dissous. Quelle masse de sable (en g) reste sur le filtre, en supposant une récupération totale ?',lambda a,b,c:a,'Le filtre retient le sable insoluble, pas le sel dissous.','Les {a} g de sable se retrouvent sur le filtre.'),
 'Masse, volume et masse volumique': ('Un objet a une masse de {a*b} g et un volume de {b} cm³. Quelle est sa masse volumique en g/cm³ ?',lambda a,b,c:a,'Utilise ρ = m / V avec les unités indiquées.','Divise {a*b} g par {b} cm³.'),
 'L’air et les gaz': ('Une seringue fermée contient {a+b} mL d’air. On réduit son volume de {b} mL. Quel est le nouveau volume en mL ?',lambda a,b,c:a,'On réduit le volume initial, sans retirer le gaz.','Calcule {a+b}−{b} mL.'),
 'Transformations physiques et chimiques': ('Une réaction a lieu en récipient hermétiquement fermé. La masse totale avant réaction est {a*b} g. Quelle masse totale trouve-t-on après (en g) ?',lambda a,b,c:a*b,'Dans un système fermé, la masse totale est conservée.','Le récipient ne perd ni ne gagne de matière : conserve {a*b} g.'),
 'Trajectoires et vitesses': ('Un vélo parcourt {a*b} km en {a} h. Quelle est sa vitesse moyenne en km/h ?',lambda a,b,c:b,'Applique v = distance / durée.','Divise {a*b} km par {a} h.'),
 'Circuits en série et dérivation': ('Dans un circuit simple en série, {a} lampes sont alimentées. Si l’une est retirée, combien restent allumées ?',lambda a,b,c:0,'En série, retirer une lampe ouvre la seule boucle.','Toutes les {a} lampes sont sur le même trajet du courant.'),
 'Mesurer la tension et l’intensité': ('Un voltmètre affiche {a} V aux bornes d’une lampe. Quelle est la tension mesurée en volts ?',lambda a,b,c:a,'Lis la valeur affichée et son unité ; le voltmètre mesure la tension.','La lecture est {a} V : aucune conversion n’est nécessaire.'),
 'Conversions et transferts d’énergie': ('Un appareil reçoit {a+b} J d’énergie et en transfère {a} J sous forme mécanique. Combien de joules sont transférés sous d’autres formes ?',lambda a,b,c:b,'L’énergie reçue se répartit entre les formes de sortie.','Soustrais {a} J de {a+b} J.'),
 'Propagation de la lumière': ('Une source éclaire {a} écrans placés sur la même ligne. On interpose un écran parfaitement opaque qui bloque le faisceau avant eux. Combien reçoivent encore directement ce faisceau ?',lambda a,b,c:0,'Un obstacle opaque bloque la lumière directe dans cette direction.','Le faisceau ne peut pas traverser cet écran pour atteindre les {a} autres.'),
 'Sons et vibrations': ('Une membrane réalise {a*b} vibrations en {a} secondes. Quelle est sa fréquence en hertz ?',lambda a,b,c:b,'La fréquence est le nombre de vibrations par seconde.','Divise {a*b} vibrations par {a} s.'),
}

# Une seconde famille de problèmes, pour éviter six répétitions du même calcul.
SCI_APPS_ALT = {
 'Solides, liquides et gaz': ('Une bouteille contient {a+b} mL d’eau. On prélève {b} mL. Quel volume de liquide reste dans la bouteille (en mL) ?',lambda a,b,c:a,'Une partie du liquide est prélevée ; son volume total diminue.','Soustrais {b} mL du volume initial de {a+b} mL.'),
 'La matière à l’échelle des particules': ('Un récipient fermé contient {a+b} particules. {b} particules passent de la zone A à la zone B à l’intérieur du récipient. Combien de particules reste-t-il dans tout le récipient ?',lambda a,b,c:a+b,'Changer de place à l’intérieur d’un récipient fermé ne supprime pas les particules.','Compte les particules dans A et dans B ensemble, sans en soustraire.'),
 'Fusion, solidification et évaporation': ('Une masse de {a+b} g d’eau liquide se solidifie entièrement dans un récipient fermé. Quelle masse de glace obtient-on en g ?',lambda a,b,c:a+b,'La solidification est un changement d’état et ne détruit pas la matière.','La masse initiale est {a+b} g ; le récipient reste fermé.'),
 'Mélanges homogènes et hétérogènes': ('Un bécher contient {a+b} mL d’eau avec du sable visible. On récupère {b} mL d’eau par décantation sans entraîner de sable. Quel volume d’eau reste dans le bécher (en mL), en supposant les volumes indiqués ?',lambda a,b,c:a,'Seule une partie du liquide est transvasée.','Calcule {a+b}−{b} mL.'),
 'Dissolution dans l’eau': ('Une solution contient {a+b} g au total, dont {b} g de sel. Quelle est la masse du solvant en g ?',lambda a,b,c:a,'La masse totale d’une solution est celle du soluté plus celle du solvant.','Soustrais la masse du sel {b} g de la masse totale {a+b} g.'),
 'Masse et volume': ('Une éprouvette contient {a+b} mL d’eau. On retire {b} mL. Quel volume d’eau reste (en mL) ?',lambda a,b,c:a,'On enlève du liquide sans modifier son unité.','Soustrais {b} mL de {a+b} mL.'),
 'Décrire un mouvement': ('Un objet parcourt {a*b} m en {a} secondes à vitesse constante. Quelle est sa vitesse en m/s ?',lambda a,b,c:b,'À vitesse constante, la vitesse est la distance divisée par la durée.','Divise {a*b} m par {a} s.'),
 'Sources et transformations d’énergie': ('Une ampoule reçoit {a+b} J d’énergie, dont {b} J sont convertis en lumière. Quelle énergie (en J) prend une autre forme ?',lambda a,b,c:a,'Fais un bilan énergétique : énergie reçue = somme des transferts.','Retire {b} J d’énergie lumineuse à {a+b} J reçus.'),
 'Premiers circuits électriques': ('Une pile alimente {a} lampes en série avec un interrupteur. Quand on ferme l’interrupteur et que les lampes fonctionnent, combien peuvent s’allumer ?',lambda a,b,c:a,'Fermer l’interrupteur rétablit le trajet du courant dans l’unique boucle.','Les {a} lampes appartiennent à cette boucle complète.'),
 'Lumière, ombres et sources': ('Une salle est éclairée par {a+b} lampes. On en éteint {b}, puis on en rallume {c}. Combien sont allumées ?',lambda a,b,c:a+c,'Compte les sources encore allumées après extinction, puis ajoute celles rallumées.','Calcule {a+b}−{b}+{c}.'),
 'Séparer les mélanges': ('On verse {a+b} g de sable sec dans un filtre ; on récupère {b} g de sable après avoir renversé accidentellement une partie du contenu. Quelle masse (en g) est perdue ?',lambda a,b,c:a,'Fais un bilan de matière entre ce qui a été versé et récupéré.','Soustrais les {b} g récupérés aux {a+b} g initiaux.'),
 'Masse, volume et masse volumique': ('Un bloc a un volume de {b} cm³ et une masse volumique de {a} g/cm³. Quelle est sa masse en grammes ?',lambda a,b,c:a*b,'La masse vaut masse volumique multipliée par volume.','Effectue {a}×{b}.'),
 'L’air et les gaz': ('Une seringue contient {a} mL d’air. On augmente le volume disponible de {b} mL sans ajouter d’air. Quel volume (en mL) occupe alors le gaz ?',lambda a,b,c:a+b,'Un gaz remplit l’espace disponible dans son récipient.','Ajoute {b} mL au volume initial {a} mL.'),
 'Transformations physiques et chimiques': ('Une réaction dans un récipient fermé met en jeu {a} g de réactif A et {b} g de réactif B. Quelle est la masse totale des produits (en g) si tous les réactifs sont consommés ?',lambda a,b,c:a+b,'Dans un système fermé, la masse totale des produits égale celle des réactifs consommés.','Additionne {a} g et {b} g.'),
 'Trajectoires et vitesses': ('Un mobile se déplace à {a} km/h durant {b} heures à vitesse constante. Quelle distance parcourt-il (en km) ?',lambda a,b,c:a*b,'À vitesse constante, distance = vitesse × durée.','Multiplie {a} km/h par {b} h.'),
 'Circuits en série et dérivation': ('Deux branches en dérivation contiennent respectivement {a} et {b} lampes. Toutes fonctionnent. Combien de lampes sont allumées au total ?',lambda a,b,c:a+b,'Les deux branches sont alimentées simultanément.','Additionne les {a} lampes de la première branche et les {b} autres.'),
 'Mesurer la tension et l’intensité': ('Un ampèremètre indique {a} A. On obtient ensuite une hausse de {b} A. Quelle intensité indique-t-il en ampères ?',lambda a,b,c:a+b,'Une hausse d’intensité s’ajoute à la lecture initiale.','Additionne {a} A et {b} A.'),
 'Conversions et transferts d’énergie': ('Un dispositif transfère {a} J sous forme lumineuse et {b} J sous forme thermique. Quelle énergie totale (en J) a-t-il transférée sous ces deux formes ?',lambda a,b,c:a+b,'Le bilan additionne les formes d’énergie transférées.','Ajoute {a} J et {b} J.'),
 'Propagation de la lumière': ('On allume {a+b} lampes qui éclairent un écran. On place un cache opaque devant {b} lampes, qui bloque totalement leur lumière directe. Combien de lampes éclairent encore directement l’écran ?',lambda a,b,c:a,'Les lampes dont les rayons sont interceptés n’éclairent plus directement l’écran.','Soustrais les {b} lampes masquées des {a+b} sources.'),
 'Sons et vibrations': ('Une membrane vibre à {b} Hz pendant {a} secondes. Combien d’oscillations réalise-t-elle ?',lambda a,b,c:a*b,'La fréquence est le nombre de vibrations par seconde.','Multiplie {b} vibrations/s par {a} s.'),
}

# Première aide conceptuelle liée au chapitre, pour les QCM scientifiques.
# La deuxième aide de chaque item s'appuie sur une proposition de CE QCM.
SCIENCE_CONCEPT_HINTS = {
 'Solides, liquides et gaz': 'Demande-toi si la matière garde sa forme, son volume, ou peut occuper tout le récipient.',
 'La matière à l’échelle des particules': 'Compare l’espacement et la mobilité des particules ; changer d’état ne crée pas de nouvelles particules.',
 'Fusion, solidification et évaporation': 'Identifie précisément l’état de départ et celui d’arrivée de la matière.',
 'Mélanges homogènes et hétérogènes': 'Regarde si les constituants sont visibles séparément à l’œil nu, puis identifie ce que sépare la technique proposée.',
 'Dissolution dans l’eau': 'Sépare les rôles du solvant, du soluté et de la solution : le soluté ne disparaît pas en se dissolvant.',
 'Masse et volume': 'La masse indique combien de matière on mesure ; le volume mesure l’espace occupé. Repère la grandeur demandée.',
 'Décrire un mouvement': 'Décris d’abord le chemin suivi par l’objet, puis vérifie si sa vitesse change au cours du temps.',
 'Sources et transformations d’énergie': 'Identifie ce que l’appareil reçoit et les formes d’énergie qu’il transfère à son environnement.',
 'Premiers circuits électriques': 'Suis la boucle du courant depuis le générateur : est-elle complète ou interrompue ?',
 'Lumière, ombres et sources': 'Repère si l’objet produit lui-même de la lumière ou renvoie celle d’une autre source.',
 'Séparer les mélanges': 'Cherche si tu veux retenir un solide non dissous, séparer deux phases visibles, ou récupérer un solide dissous.',
 'Masse, volume et masse volumique': 'Distingue masse et volume : compare la quantité de matière contenue dans un même volume.',
 'L’air et les gaz': 'Imagine les particules du gaz réparties dans tout le volume disponible et compare ce qui change lors d’une compression.',
 'Transformations physiques et chimiques': 'Vérifie si de nouvelles espèces chimiques apparaissent ou si seule la forme ou l’état change.',
 'Trajectoires et vitesses': 'Sépare la forme de la trajectoire de la mesure de vitesse : celle-ci compare distance parcourue et durée.',
 'Circuits en série et dérivation': 'Compte les chemins possibles du courant : une seule boucle ou plusieurs branches indépendantes ?',
 'Mesurer la tension et l’intensité': 'Identifie d’abord la grandeur demandée, puis demande-toi si l’appareil observe le courant traversant un dipôle ou ses bornes.',
 'Conversions et transferts d’énergie': 'Dresse un bilan entre l’énergie reçue et les formes d’énergie transférées : utile ou dissipée.',
 'Propagation de la lumière': 'Trace mentalement le trajet de la lumière de la source à l’objet puis à l’œil ou à l’écran.',
 'Sons et vibrations': 'Repère ce qui vibre et distingue hauteur du son, intensité et milieu de propagation.',
}

def sci_exercises(title, level):
    skills=SCI_SKILLS[title]
    ex=[]
    for i,skill in enumerate(skills):
        prompt,ans,w1,w2,correction=skill
        # Hints précis écrits à partir du concept exact de l’item, sans dire la réponse.
        hint1 = SCIENCE_CONCEPT_HINTS[title]
        hint2 = f'La proposition « {w2} » ne correspond pas à la situation donnée. Écarte-la, puis distingue les deux autres en utilisant la propriété étudiée dans « {title} ».'
        ex.append(question(f'Exercice {i+1} — {prompt[:55]}',prompt,ans,correction,hint1,hint2,1 if i<2 else 2 if i<4 else 3,[ans,w1,w2],method=correction))
    for i in range(6):
        template,calc,h1,h2=(SCI_APPS if i<3 else SCI_APPS_ALT)[title]
        a=[6,9,12,15,18,21][i]
        b=[4,5,7,8,9,11][i]
        c=[2,3,4,5,6,7][i]
        st=re.sub(r'\{([^{}]+)\}',lambda match: str(eval(match.group(1), {'__builtins__':{}},{'a':a,'b':b,'c':c})),template)
        result=calc(a,b,c)
        ex.append(question(f'Exercice {i+7} — Application',st,str(result),f'{h1} Résultat : {result}.',h1,re.sub(r'\{([^{}]+)\}',lambda match: str(eval(match.group(1), {'__builtins__':{}},{'a':a,'b':b,'c':c})),h2),1 if i==0 else 2 if i in (1,2) else 3,method=h1))
    return ex

def make_chapter(config, i, subject, level):
    title,summary,p1,t2,p2,t3,p3=config
    lessons=[
        {'title':'Comprendre : '+title,'body':blocks({'type':'paragraph','content':p1},{'type':'note','content':'Objectif : '+summary}),'order_index':1},
        {'title':t2,'body':blocks({'type':'paragraph','content':p2},{'type':'note','content':'À retenir : '+p2}),'order_index':2},
        {'title':t3,'body':blocks({'type':'paragraph','content':p3},{'type':'note','content':'Vérifie que tu as compris : '+p3}),'order_index':3},
    ]
    if subject=='mathematiques':
        theme=i if level=='6e' else i+15
        exercises=[exercise_from_math(theme,k,level) for k in range(12)]
    else: exercises=sci_exercises(title,level)
    for k,ex in enumerate(exercises): ex['order_index']=k+1
    return {'subject':subject,'level':level,'order_index':i+1,'title':title,'summary':summary,'lessons':lessons,'exercises':exercises}

def generate(level):
    subjects=(MATH_6,SCI_6) if level=='6e' else (MATH_5,SCI_5)
    chapters=[make_chapter(cfg,i,slug,level) for slug,arr in zip(('mathematiques','physique-chimie'),subjects) for i,cfg in enumerate(arr)]
    pack={'pack_id':f'fr-{level}-2026-v10','title':f'StudySprint V10 — {level}, mathématiques et sciences, premier catalogue','level':level,'subjects':SUBJECTS,'chapters':chapters}
    assert len(chapters)==25 and sum(len(ch['lessons']) for ch in chapters)==75
    assert sum(len(ch['exercises']) for ch in chapters)==300
    keys=set()
    for ch in chapters:
        for ex in ch['exercises']:
            key=(ch['title'],ex['statement'])
            if key in keys: raise AssertionError(('duplicate',key))
            keys.add(key)
            assert len(ex['hints'])==2 and ex['correct_answer'] and ex['correction']
            if ex['options']:
                assert ex['correct_answer'] in ex['options']
                assert len(set(ex['options']))==len(ex['options']), (ch['title'],ex)
    filename=OUT/f'{level}_2026_v10.json'
    filename.write_text(json.dumps(pack,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(level,'chapters',len(chapters),'lessons',sum(len(ch['lessons']) for ch in chapters),'exercises',sum(len(ch['exercises']) for ch in chapters),'size',filename.stat().st_size)

if __name__=='__main__':
    generate('6e');generate('5e')
